<?php
declare(strict_types=1);

function isAreaLeader(PDO $pdo, int $userId): bool
{
    $statement=$pdo->prepare("SELECT 1 FROM user_roles ur INNER JOIN roles r ON r.id=ur.role_id WHERE ur.user_id=:user AND ur.is_active=1 AND r.is_active=1 AND r.code IN ('AREA_ADMIN','AREA_MANAGER') LIMIT 1");
    $statement->execute(['user'=>$userId]);
    return (bool)$statement->fetchColumn();
}

function userHasPermission(PDO $pdo, int $userId, string $moduleCode, string $actionCode): bool
{
    if(isSuperAdmin($pdo,$userId)) return true;
    $deny=$pdo->prepare("SELECT 1 FROM user_permission_overrides o INNER JOIN permissions p ON p.id=o.permission_id INNER JOIN app_modules m ON m.id=p.module_id WHERE o.user_id=:user AND o.decision='DENY' AND m.code=:module AND p.action_code=:action LIMIT 1");
    $deny->execute(['user'=>$userId,'module'=>$moduleCode,'action'=>$actionCode]);
    if($deny->fetchColumn()) return false;
    $allow=$pdo->prepare("SELECT 1 FROM permissions p INNER JOIN app_modules m ON m.id=p.module_id WHERE m.code=:module AND p.action_code=:action AND (EXISTS(SELECT 1 FROM user_roles ur INNER JOIN role_permissions rp ON rp.role_id=ur.role_id WHERE ur.user_id=:role_user AND ur.is_active=1 AND rp.permission_id=p.id) OR EXISTS(SELECT 1 FROM user_permission_overrides o WHERE o.user_id=:override_user AND o.permission_id=p.id AND o.decision='ALLOW')) LIMIT 1");
    $allow->execute(['module'=>$moduleCode,'action'=>$actionCode,'role_user'=>$userId,'override_user'=>$userId]);
    return (bool)$allow->fetchColumn();
}

function requireArea(PDO $pdo, array $user, array $areaCodes): void
{
    if(isSuperAdmin($pdo,(int)$user['id']))return;
    $marks=implode(',',array_fill(0,count($areaCodes),'?'));$statement=$pdo->prepare("SELECT 1 FROM areas WHERE id=? AND code IN ({$marks}) AND is_active=1");$statement->execute(array_merge([(int)$user['primary_area_id']],$areaCodes));if(!$statement->fetchColumn())failRequest('Esta captura corresponde a otra área.',403);
}

function buildLookups(PDO $pdo, array $user, bool $isAdmin): array
{
    $areas=$isAdmin?safeRows($pdo,"SELECT id,code,name FROM areas WHERE is_active=1 ORDER BY name"):safeRows($pdo,"SELECT id,code,name FROM areas WHERE id=:id AND is_active=1",['id'=>$user['primary_area_id']]);
    $roles=$isAdmin?safeRows($pdo,"SELECT id,code,name FROM roles WHERE is_active=1 AND code<>'SUPER_ADMIN' ORDER BY is_system DESC,name"):safeRows($pdo,"SELECT id,code,name FROM roles WHERE is_active=1 AND code IN ('OPERATOR','APPROVER','VIEWER','TECHNICIAN') ORDER BY id");
    $moduleSql="SELECT DISTINCT m.id,m.code,m.name,m.sort_order FROM app_modules m WHERE m.is_active=1 AND m.code IN ('DASHBOARD','WAREHOUSE_RAW','WAREHOUSE_PACKAGING','WAREHOUSE_SPARES','WAREHOUSE_FINISHED','INVENTORY','COUNTS','PURCHASING','QUALITY','QUALITY_ANALYTICS','FILLING','EXTRACTION','MAINTENANCE','FORECAST','MRP','SHIPPING','RETURNS')";
    $modules=$isAdmin?safeRows($pdo,$moduleSql." ORDER BY m.sort_order"):safeRows($pdo,$moduleSql." AND EXISTS(SELECT 1 FROM permissions p WHERE p.module_id=m.id AND p.action_code='VIEW' AND (EXISTS(SELECT 1 FROM user_roles ur INNER JOIN role_permissions rp ON rp.role_id=ur.role_id WHERE ur.user_id=:user1 AND ur.is_active=1 AND rp.permission_id=p.id) OR EXISTS(SELECT 1 FROM user_permission_overrides o WHERE o.user_id=:user2 AND o.permission_id=p.id AND o.decision='ALLOW'))) ORDER BY m.sort_order",['user1'=>$user['id'],'user2'=>$user['id']]);
    $canInventory=$isAdmin||userHasPermission($pdo,(int)$user['id'],'INVENTORY','VIEW')||userHasPermission($pdo,(int)$user['id'],'INITIAL_INVENTORY','VIEW')||userHasPermission($pdo,(int)$user['id'],'COUNTS','VIEW')||userHasPermission($pdo,(int)$user['id'],'RECEIVING','VIEW')||hasAnyPermissionV14($pdo,(int)$user['id'],['WAREHOUSE_RAW','WAREHOUSE_PACKAGING','WAREHOUSE_SPARES','WAREHOUSE_FINISHED'],'VIEW');
    $canCatalogs=$isAdmin||userHasPermission($pdo,(int)$user['id'],'CATALOGS','VIEW')||hasAnyPermissionV14($pdo,(int)$user['id'],['WAREHOUSE_RAW','WAREHOUSE_PACKAGING','WAREHOUSE_SPARES','WAREHOUSE_FINISHED','FILLING'],'VIEW');
    $canForecast=$isAdmin||userHasPermission($pdo,(int)$user['id'],'FORECAST','VIEW')||userHasPermission($pdo,(int)$user['id'],'MRP','VIEW')||userHasPermission($pdo,(int)$user['id'],'FILLING','VIEW');
    $canSuppliers=$isAdmin||userHasPermission($pdo,(int)$user['id'],'PURCHASING','VIEW')||userHasPermission($pdo,(int)$user['id'],'APPOINTMENTS','VIEW')||userHasPermission($pdo,(int)$user['id'],'RECEIVING','VIEW');
    $canCustomers=$isAdmin||$canForecast||userHasPermission($pdo,(int)$user['id'],'SHIPPING','VIEW')||userHasPermission($pdo,(int)$user['id'],'RETURNS','VIEW')||userHasPermission($pdo,(int)$user['id'],'PRODUCTION','VIEW');
    $canMaintenance=$isAdmin||userHasPermission($pdo,(int)$user['id'],'MAINTENANCE','VIEW');
    $userAreaCode=(string)($areas[0]['code']??'');
    [$maintenanceFilter,$maintenanceParams]=maintenanceVisibility($pdo,$user,'r');
    return [
        'areas'=>$areas,'roles'=>$roles,'modules'=>$modules,
        'warehouses'=>$canInventory||$canCatalogs?safeRows($pdo,"SELECT id,code,name,warehouse_type FROM warehouses WHERE is_active=1 AND code NOT LIKE 'EJ-%' ORDER BY name"):[],
        'locations'=>$canInventory||$canCatalogs?safeRows($pdo,"SELECT l.id,l.warehouse_id,l.code,l.name,l.location_type,l.is_blocked,w.name AS warehouse_name,w.warehouse_type FROM warehouse_locations l INNER JOIN warehouses w ON w.id=l.warehouse_id WHERE l.is_active=1 AND w.is_active=1 AND w.code NOT LIKE 'EJ-%' ORDER BY w.name,l.name"):[],
        'items'=>$canInventory||$canCatalogs?safeRows($pdo,"SELECT i.id,i.sku,i.name,i.item_type,i.lot_controlled,i.quality_required,i.base_uom_id,u.code AS uom_code,u.name AS uom_name FROM items i INNER JOIN units_of_measure u ON u.id=i.base_uom_id WHERE i.is_active=1 AND i.sku NOT LIKE 'EJ-%' ORDER BY i.name"):[],
        'categories'=>$canCatalogs?safeRows($pdo,"SELECT code,name FROM item_categories WHERE is_active=1 ORDER BY name"):[],
        'units'=>$canCatalogs?safeRows($pdo,"SELECT code,name FROM units_of_measure ORDER BY name"):[],
        'finishedGoods'=>$canForecast||$canCatalogs?safeRows($pdo,"SELECT id,sku,name FROM items WHERE is_active=1 AND item_type='FINISHED_GOOD' AND sku NOT LIKE 'EJ-%' ORDER BY name"):[],
        'suppliers'=>$canSuppliers||($canCatalogs&&($isAdmin||$userAreaCode==='COMPRAS'))?safeRows($pdo,"SELECT id,supplier_code,COALESCE(trade_name,legal_name) AS name FROM suppliers WHERE is_active=1 AND supplier_code NOT LIKE 'EJ-%' ORDER BY name"):[],
        'customers'=>$canCustomers||($canCatalogs&&($isAdmin||$userAreaCode==='VENTAS'))?safeRows($pdo,"SELECT id,customer_code,COALESCE(trade_name,legal_name) AS name FROM customers WHERE is_active=1 AND customer_code NOT LIKE 'EJ-%' ORDER BY name"):[],
        'assets'=>$canMaintenance?safeRows($pdo,"SELECT id,asset_code,asset_name FROM maintenance_assets WHERE is_active=1 AND asset_code NOT LIKE 'EJ-%' ORDER BY asset_name"):[],
        'technicians'=>$canMaintenance&&isMaintenanceLeader($pdo,$user)?safeRows($pdo,"SELECT u.id,u.display_name AS name,u.email,t.specialties,t.phone FROM maintenance_technicians t INNER JOIN app_users u ON u.id=t.user_id WHERE t.is_active=1 AND u.status='ACTIVE' ORDER BY u.display_name"):[],
        'maintenanceRequests'=>$canMaintenance?safeRows($pdo,"SELECT r.id,r.request_number,r.title,r.status FROM maintenance_work_requests r {$maintenanceFilter} AND r.status NOT IN ('VERIFIED','CANCELLED') ORDER BY r.created_at DESC",$maintenanceParams):[],
    ];
}

function maintenanceVisibility(PDO $pdo, array $user, string $alias='r'): array
{
    if(isSuperAdmin($pdo,(int)$user['id'])||isMaintenanceLeader($pdo,$user))return ['WHERE 1=1',[]];
    if(isAreaLeader($pdo,(int)$user['id']))return ["WHERE ({$alias}.requesting_area_id=:visible_area OR {$alias}.requested_by=:visible_requester OR EXISTS(SELECT 1 FROM maintenance_work_assignments visible_assignment WHERE visible_assignment.work_request_id={$alias}.id AND visible_assignment.technician_user_id=:visible_technician AND visible_assignment.assignment_status<>'CANCELLED'))",['visible_area'=>$user['primary_area_id'],'visible_requester'=>$user['id'],'visible_technician'=>$user['id']]];
    return ["WHERE ({$alias}.requested_by=:visible_requester OR EXISTS(SELECT 1 FROM maintenance_work_assignments visible_assignment WHERE visible_assignment.work_request_id={$alias}.id AND visible_assignment.technician_user_id=:visible_technician AND visible_assignment.assignment_status<>'CANCELLED'))",['visible_requester'=>$user['id'],'visible_technician'=>$user['id']]];
}

function buildUserList(PDO $pdo, array $user, bool $isAdmin): array
{
    $where=$isAdmin?'':'WHERE u.primary_area_id=:area';
    $params=$isAdmin?[]:['area'=>$user['primary_area_id']];
    return safeRows($pdo,"SELECT
        u.id,u.display_name AS name,u.email,u.phone_number AS phone,u.primary_area_id AS primaryAreaId,
        COALESCE(a.name,'Sin área') AS area,
        COALESCE((SELECT r.name FROM user_roles ur INNER JOIN roles r ON r.id=ur.role_id WHERE ur.user_id=u.id AND ur.is_active=1 ORDER BY r.id LIMIT 1),'Sin rol') AS role,
        COALESCE((SELECT r.code FROM user_roles ur INNER JOIN roles r ON r.id=ur.role_id WHERE ur.user_id=u.id AND ur.is_active=1 ORDER BY r.id LIMIT 1),'') AS roleCode,
        COALESCE((SELECT GROUP_CONCAT(DISTINCT m.name ORDER BY m.sort_order SEPARATOR ', ')
          FROM app_modules m INNER JOIN permissions p ON p.module_id=m.id AND p.action_code='VIEW'
          WHERE m.is_active=1
            AND (EXISTS(SELECT 1 FROM user_roles ur INNER JOIN role_permissions rp ON rp.role_id=ur.role_id WHERE ur.user_id=u.id AND ur.is_active=1 AND rp.permission_id=p.id)
              OR EXISTS(SELECT 1 FROM user_permission_overrides allow_override WHERE allow_override.user_id=u.id AND allow_override.permission_id=p.id AND allow_override.decision='ALLOW'))
            AND NOT EXISTS(SELECT 1 FROM user_permission_overrides deny_override WHERE deny_override.user_id=u.id AND deny_override.permission_id=p.id AND deny_override.decision='DENY')),'Acceso total') AS modules,
        COALESCE((SELECT GROUP_CONCAT(DISTINCT m.code ORDER BY m.sort_order SEPARATOR ',')
          FROM app_modules m INNER JOIN permissions p ON p.module_id=m.id AND p.action_code='VIEW'
          WHERE m.is_active=1
            AND (EXISTS(SELECT 1 FROM user_roles ur INNER JOIN role_permissions rp ON rp.role_id=ur.role_id WHERE ur.user_id=u.id AND ur.is_active=1 AND rp.permission_id=p.id)
              OR EXISTS(SELECT 1 FROM user_permission_overrides allow_override WHERE allow_override.user_id=u.id AND allow_override.permission_id=p.id AND allow_override.decision='ALLOW'))
            AND NOT EXISTS(SELECT 1 FROM user_permission_overrides deny_override WHERE deny_override.user_id=u.id AND deny_override.permission_id=p.id AND deny_override.decision='DENY')),'') AS moduleCodes,
        EXISTS(SELECT 1 FROM user_roles ur INNER JOIN roles r ON r.id=ur.role_id WHERE ur.user_id=u.id AND ur.is_active=1 AND r.code='SUPER_ADMIN') AS isSystemAdmin,
        u.status
      FROM app_users u LEFT JOIN areas a ON a.id=u.primary_area_id {$where}
      ORDER BY u.display_name",$params);
}

function buildAreaDashboard(PDO $pdo, array $area): array
{
    $areaCode=(string)($area['code']??'SIN_AREA');
    $dashboard=[
        'title'=>'Panel de '.($area['name']??'mi área'),
        'metrics'=>[],
        'inventoryByWarehouse'=>safeRows($pdo,"SELECT w.name AS label,w.warehouse_type AS warehouseType,COUNT(DISTINCT a.item_id) AS items,COALESCE(SUM(a.on_hand_qty),0) AS quantity FROM vw_inventory_on_hand a INNER JOIN warehouses w ON w.id=a.warehouse_id GROUP BY w.id,w.name,w.warehouse_type ORDER BY w.name"),
        'criticalMaterials'=>safeRows($pdo,"SELECT i.name AS item,i.sku,i.item_type AS type,COALESCE(SUM(v.available_qty),0) AS available,i.reorder_point,u.name AS uom,CASE WHEN COALESCE(SUM(v.available_qty),0)<=0 THEN 'Sin existencia' ELSE 'Por debajo del punto de reorden' END AS status FROM items i INNER JOIN units_of_measure u ON u.id=i.base_uom_id LEFT JOIN vw_inventory_availability v ON v.item_id=i.id WHERE i.is_active=1 AND i.item_type<>'SERVICE' GROUP BY i.id,i.name,i.sku,i.item_type,i.reorder_point,u.name HAVING i.reorder_point>0 AND available<=i.reorder_point ORDER BY available/i.reorder_point,i.name LIMIT 25"),
        'highFlow'=>safeRows($pdo,"SELECT i.name AS item,i.sku,i.item_type AS type,SUM(ABS(l.quantity_delta)) AS quantity,u.name AS uom FROM inventory_movement_lines l INNER JOIN inventory_movements m ON m.id=l.movement_id INNER JOIN items i ON i.id=l.item_id INNER JOIN units_of_measure u ON u.id=l.uom_id WHERE m.status='POSTED' AND l.quantity_delta<0 AND m.posted_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 30 DAY) GROUP BY i.id,i.name,i.sku,i.item_type,u.name ORDER BY quantity DESC LIMIT 15"),
        'planShortages'=>safeRows($pdo,"SELECT i.name AS item,i.sku,i.item_type AS type,SUM(r.net_requirement) AS shortage,MIN(r.requirement_date) AS needDate,u.name AS uom FROM mrp_requirements r INNER JOIN items i ON i.id=r.item_id INNER JOIN units_of_measure u ON u.id=i.base_uom_id WHERE r.mrp_run_id=(SELECT MAX(id) FROM mrp_runs WHERE status='COMPLETED') AND r.status='SHORTAGE' GROUP BY i.id,i.name,i.sku,i.item_type,u.name ORDER BY needDate,shortage DESC LIMIT 30"),
        'forecastCompliance'=>safeRows($pdo,"SELECT i.name AS item,i.sku,i.item_type AS type,SUM(f.forecast_qty) AS forecastQty,COALESCE(stock.available,0) AS availableQty,ROUND(LEAST(100,COALESCE(stock.available,0)/NULLIF(SUM(f.forecast_qty),0)*100),1) AS compliance FROM forecast_versions v INNER JOIN forecast_lines f ON f.forecast_version_id=v.id INNER JOIN items i ON i.id=f.finished_item_id LEFT JOIN (SELECT item_id,SUM(available_qty) AS available FROM vw_inventory_availability GROUP BY item_id) stock ON stock.item_id=i.id WHERE v.is_current=1 AND f.period_start>=DATE_FORMAT(UTC_DATE(),'%Y-%m-01') GROUP BY i.id,i.name,i.sku,i.item_type,stock.available ORDER BY compliance,i.name LIMIT 25"),
    ];
    if($areaCode==='COMPRAS'){
        $dashboard['metrics']=[
            ['label'=>'Llegadas próximas','value'=>safeScalar($pdo,"SELECT COUNT(*) FROM inbound_appointments WHERE scheduled_start BETWEEN UTC_TIMESTAMP() AND DATE_ADD(UTC_TIMESTAMP(),INTERVAL 7 DAY) AND status NOT IN ('COMPLETED','CANCELLED')"),'note'=>'Próximos siete días','tone'=>''],
            ['label'=>'Citas por confirmar','value'=>safeScalar($pdo,"SELECT COUNT(*) FROM inbound_appointments WHERE status IN ('PLANNED','SENT') AND scheduled_start>=UTC_TIMESTAMP()"),'note'=>'Requieren seguimiento','tone'=>'warning'],
            ['label'=>'Necesidades por comprar','value'=>safeScalar($pdo,"SELECT COUNT(*) FROM mrp_requirements WHERE status='SHORTAGE'"),'note'=>'Según el último cálculo','tone'=>'danger'],
            ['label'=>'Proveedores activos','value'=>safeScalar($pdo,"SELECT COUNT(*) FROM suppliers WHERE is_active=1"),'note'=>'Catálogo vigente','tone'=>''],
        ];
    }elseif($areaCode==='MANTENIMIENTO'){
        $dashboard['metrics']=[
            ['label'=>'Solicitudes abiertas','value'=>safeScalar($pdo,"SELECT COUNT(*) FROM maintenance_work_requests WHERE status NOT IN ('VERIFIED','CANCELLED')"),'note'=>'Pendientes de cierre','tone'=>'warning'],
            ['label'=>'Tareas en proceso','value'=>safeScalar($pdo,"SELECT COUNT(*) FROM maintenance_work_requests WHERE status='IN_PROGRESS'"),'note'=>'Con técnicos trabajando','tone'=>''],
            ['label'=>'Tareas críticas','value'=>safeScalar($pdo,"SELECT COUNT(*) FROM maintenance_work_requests WHERE priority_code='CRITICAL' AND status NOT IN ('VERIFIED','CANCELLED')"),'note'=>'Atención inmediata','tone'=>'danger'],
            ['label'=>'Horas registradas','value'=>safeScalar($pdo,"SELECT COALESCE(SUM(actual_hours),0) FROM maintenance_work_assignments"),'note'=>'Horas de intervención','tone'=>''],
        ];
    }elseif($areaCode==='CALIDAD'){
        $dashboard['metrics']=[
            ['label'=>'Solicitudes pendientes','value'=>safeScalar($pdo,"SELECT COUNT(*) FROM quality_requests WHERE status NOT IN ('COMPLETED','CANCELLED')"),'note'=>'Pendientes de dictamen','tone'=>'warning'],
            ['label'=>'Lotes bloqueados','value'=>safeScalar($pdo,"SELECT COUNT(*) FROM inventory_lots WHERE lot_status='BLOCKED'"),'note'=>'No disponibles para consumo','tone'=>'danger'],
            ['label'=>'Aprobados este mes','value'=>safeScalar($pdo,"SELECT COUNT(*) FROM quality_requests WHERE disposition='APPROVED' AND completed_at>=DATE_FORMAT(UTC_DATE(),'%Y-%m-01')"),'note'=>'Liberados por Calidad','tone'=>''],
            ['label'=>'Rechazados este mes','value'=>safeScalar($pdo,"SELECT COUNT(*) FROM quality_requests WHERE disposition='REJECTED' AND completed_at>=DATE_FORMAT(UTC_DATE(),'%Y-%m-01')"),'note'=>'Requieren seguimiento','tone'=>'danger'],
        ];
    }elseif(in_array($areaCode,['ENVASADO','PRODUCCION'],true)){
        $dashboard['metrics']=[
            ['label'=>'Órdenes abiertas','value'=>safeScalar($pdo,"SELECT COUNT(*) FROM production_orders WHERE status NOT IN ('COMPLETED','CLOSED','CANCELLED')"),'note'=>'Pendientes de terminar','tone'=>''],
            ['label'=>'Órdenes con faltantes','value'=>safeScalar($pdo,"SELECT COUNT(*) FROM production_orders WHERE status IN ('MATERIAL_CHECK','ON_HOLD')"),'note'=>'Material incompleto','tone'=>'danger'],
            ['label'=>'Listas activas','value'=>safeScalar($pdo,"SELECT COUNT(*) FROM bom_versions WHERE status='ACTIVE'"),'note'=>'Listas de materiales vigentes','tone'=>''],
            ['label'=>'Terminaciones de hoy','value'=>safeScalar($pdo,"SELECT COUNT(*) FROM production_completions WHERE completed_at>=UTC_DATE()"),'note'=>'Entradas a producto terminado','tone'=>''],
        ];
    }elseif($areaCode==='EXTRACCION'){
        $dashboard['metrics']=[
            ['label'=>'Procesos abiertos','value'=>safeScalar($pdo,"SELECT COUNT(*) FROM process_batches WHERE process_type='EXTRACTION' AND status NOT IN ('COMPLETED','CANCELLED')"),'note'=>'Lotes en proceso','tone'=>''],
            ['label'=>'Debajo de meta','value'=>safeScalar($pdo,"SELECT COUNT(*) FROM extraction_runs WHERE beans_count/operating_hours<target_beans_hour"),'note'=>'Menos de 13 contenedores por hora','tone'=>'warning'],
            ['label'=>'Pendientes de Calidad','value'=>safeScalar($pdo,"SELECT COUNT(*) FROM quality_requests WHERE request_type='IN_PROCESS' AND status NOT IN ('COMPLETED','CANCELLED')"),'note'=>'Muestras sin dictamen','tone'=>'warning'],
            ['label'=>'Procesos de hoy','value'=>safeScalar($pdo,"SELECT COUNT(*) FROM process_batches WHERE process_type='EXTRACTION' AND started_at>=UTC_DATE()"),'note'=>'Lotes alimentados','tone'=>''],
        ];
    }else{
        $dashboard['metrics']=[
            ['label'=>'Productos con existencia','value'=>safeScalar($pdo,"SELECT COUNT(DISTINCT item_id) FROM vw_inventory_on_hand"),'note'=>'Inventario contabilizado','tone'=>''],
            ['label'=>'Materiales críticos','value'=>count($dashboard['criticalMaterials']),'note'=>'En punto de reorden','tone'=>'danger'],
            ['label'=>'Pendientes de Calidad','value'=>safeScalar($pdo,"SELECT COUNT(*) FROM quality_requests WHERE status NOT IN ('COMPLETED','CANCELLED')"),'note'=>'Esperan dictamen','tone'=>'warning'],
            ['label'=>'Órdenes en riesgo','value'=>safeScalar($pdo,"SELECT COUNT(*) FROM production_orders WHERE status IN ('MATERIAL_CHECK','ON_HOLD')"),'note'=>'Posible incumplimiento','tone'=>'danger'],
        ];
    }
    return $dashboard;
}

function buildPurchaseDashboard(PDO $pdo): array
{
    return [
        'upcoming'=>safeRows($pdo,"SELECT a.appointment_number AS id,DATE_FORMAT(a.scheduled_start,'%d %b %Y · %H:%i') AS scheduled,COALESCE(s.trade_name,s.legal_name) AS supplier,a.notes AS material,a.status,COALESCE(a.delay_minutes,0) AS delayMinutes FROM inbound_appointments a INNER JOIN suppliers s ON s.id=a.supplier_id WHERE a.scheduled_start>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 1 DAY) AND a.status NOT IN ('COMPLETED','CANCELLED') ORDER BY a.scheduled_start LIMIT 100"),
        'needs'=>safeRows($pdo,"SELECT i.name AS item,i.sku,r.net_requirement AS shortage,r.requirement_date AS needDate,u.name AS uom,COALESCE(s.trade_name,s.legal_name,'Proveedor por definir') AS supplier FROM mrp_requirements r INNER JOIN items i ON i.id=r.item_id INNER JOIN units_of_measure u ON u.id=i.base_uom_id LEFT JOIN supplier_items si ON si.item_id=i.id AND si.is_preferred=1 LEFT JOIN suppliers s ON s.id=si.supplier_id WHERE r.status='SHORTAGE' AND r.mrp_run_id=(SELECT MAX(id) FROM mrp_runs WHERE status='COMPLETED') ORDER BY r.requirement_date,i.name LIMIT 200"),
    ];
}

function buildMaintenanceWork(PDO $pdo, array $user): array
{
    [$filter,$params]=maintenanceVisibility($pdo,$user,'r');
    $params['current_user']=$user['id'];
    return safeRows($pdo,"SELECT r.id,r.request_number AS requestNumber,r.title,r.description,COALESCE(a.asset_name,'Sin equipo asociado') AS asset,ar.name AS requestingArea,r.location_description AS location,r.requested_materials AS materials,r.priority_code AS priority,DATE_FORMAT(r.needed_at,'%d %b %Y · %H:%i') AS needed,r.status,COALESCE(work.technicians,'Sin técnicos asignados') AS technicians,COALESCE(work.estimated_hours,0) AS estimatedHours,COALESCE(work.actual_hours,0) AS actualHours,COALESCE(evidence.evidence_count,0) AS evidenceCount,EXISTS(SELECT 1 FROM maintenance_work_assignments own_assignment WHERE own_assignment.work_request_id=r.id AND own_assignment.technician_user_id=:current_user AND own_assignment.assignment_status<>'CANCELLED') AS canRespond FROM maintenance_work_requests r INNER JOIN areas ar ON ar.id=r.requesting_area_id LEFT JOIN maintenance_assets a ON a.id=r.asset_id LEFT JOIN (SELECT wa.work_request_id,GROUP_CONCAT(u.display_name ORDER BY u.display_name SEPARATOR ', ') AS technicians,SUM(wa.estimated_hours) AS estimated_hours,SUM(wa.actual_hours) AS actual_hours FROM maintenance_work_assignments wa INNER JOIN app_users u ON u.id=wa.technician_user_id WHERE wa.assignment_status<>'CANCELLED' GROUP BY wa.work_request_id) work ON work.work_request_id=r.id LEFT JOIN (SELECT CAST(entity_id AS UNSIGNED) AS work_request_id,COUNT(*) AS evidence_count FROM file_attachments WHERE entity_type='maintenance_work_request' GROUP BY CAST(entity_id AS UNSIGNED)) evidence ON evidence.work_request_id=r.id {$filter} ORDER BY FIELD(r.priority_code,'CRITICAL','HIGH','NORMAL','LOW'),r.needed_at",$params);
}

function buildMaintenanceUpdates(PDO $pdo, array $user): array
{
    [$filter,$params]=maintenanceVisibility($pdo,$user,'r');
    return safeRows($pdo,"SELECT u.work_request_id AS requestId,u.status,u.hours_reported AS hours,u.observations,COALESCE(a.display_name,'Sistema') AS user,DATE_FORMAT(u.created_at,'%d %b %Y · %H:%i') AS createdAt FROM maintenance_work_updates u INNER JOIN maintenance_work_requests r ON r.id=u.work_request_id LEFT JOIN app_users a ON a.id=u.updated_by {$filter} ORDER BY u.created_at DESC LIMIT 2000",$params);
}

function buildMaintenanceEvidence(PDO $pdo, array $user): array
{
    [$filter,$params]=maintenanceVisibility($pdo,$user,'r');
    return safeRows($pdo,"SELECT f.id,CAST(f.entity_id AS UNSIGNED) AS requestId,f.file_name AS fileName,f.mime_type AS mimeType,COALESCE(u.display_name,'Sistema') AS uploadedBy,DATE_FORMAT(f.uploaded_at,'%d %b %Y · %H:%i') AS uploadedAt FROM file_attachments f INNER JOIN maintenance_work_requests r ON r.id=CAST(f.entity_id AS UNSIGNED) LEFT JOIN app_users u ON u.id=f.uploaded_by {$filter} AND f.entity_type='maintenance_work_request' ORDER BY f.uploaded_at DESC LIMIT 2000",$params);
}

function buildInventoryAuditSchedules(PDO $pdo): array
{
    return safeRows($pdo,"SELECT s.id,s.schedule_name AS name,w.name AS warehouse,w.warehouse_type AS warehouseType,s.weekday_codes AS weekdays,TIME_FORMAT(s.start_time,'%H:%i') AS startTime,s.count_type AS countType,s.scope_description AS scope,s.notes,s.is_active AS isActive FROM inventory_audit_schedules s INNER JOIN warehouses w ON w.id=s.warehouse_id WHERE s.is_active=1 ORDER BY w.name,s.start_time,s.schedule_name");
}

function buildInventoryAuditDetails(PDO $pdo): array
{
    return safeRows($pdo,"SELECT c.count_number AS countNumber,DATE_FORMAT(COALESCE(c.completed_at,c.created_at),'%d %b %Y · %H:%i') AS auditDate,w.name AS warehouse,w.warehouse_type AS warehouseType,i.name AS item,i.sku,COALESCE(l.lot_code,'Sin lote') AS lot,wl.name AS location,cl.system_qty AS systemQuantity,cl.final_count_qty AS countedQuantity,cl.variance_qty AS difference,uom.name AS uom,COALESCE(cl.notes,'Sin observaciones') AS observations,COALESCE(u.display_name,'Sistema') AS countedBy FROM inventory_count_lines cl INNER JOIN inventory_counts c ON c.id=cl.inventory_count_id INNER JOIN warehouses w ON w.id=c.warehouse_id INNER JOIN items i ON i.id=cl.item_id INNER JOIN units_of_measure uom ON uom.id=i.base_uom_id INNER JOIN warehouse_locations wl ON wl.id=cl.location_id LEFT JOIN inventory_lots l ON l.id=cl.inventory_lot_id LEFT JOIN app_users u ON u.id=cl.counted_by WHERE cl.final_count_qty IS NOT NULL ORDER BY c.created_at DESC,ABS(cl.variance_qty) DESC LIMIT 3000");
}

function createInventoryAuditSchedule(PDO $pdo, array $user, array $payload): array
{
    requireArea($pdo,$user,['ALMACEN']);
    $warehouse=findOne($pdo,"SELECT id,name,warehouse_type FROM warehouses WHERE id=:id AND is_active=1",['id'=>(int)($payload['warehouse_id']??0)],'Selecciona un almacén válido.');$module=['RAW_MATERIAL'=>'WAREHOUSE_RAW','PACKAGING'=>'WAREHOUSE_PACKAGING','SPARE_PARTS'=>'WAREHOUSE_SPARES','FINISHED_GOODS'=>'WAREHOUSE_FINISHED'][$warehouse['warehouse_type']]??'COUNTS';requireAnyPermissionV14($pdo,(int)$user['id'],[$module,'COUNTS'],'CREATE');$rawDays=$payload['weekday_codes']??[];if(!is_array($rawDays))$rawDays=explode(',',(string)$rawDays);$allowed=['MON','TUE','WED','THU','FRI','SAT','SUN'];$days=array_values(array_unique(array_filter(array_map(fn($day)=>strtoupper(trim((string)$day)),$rawDays),fn($day)=>in_array($day,$allowed,true))));if(!$days)failRequest('Selecciona al menos un día de la semana.',422);$time=trim((string)($payload['start_time']??''));if(!preg_match('/^(?:[01]\d|2[0-3]):[0-5]\d$/',$time))failRequest('La hora programada no es válida.',422);$type=strtoupper((string)($payload['count_type']??'CYCLE'));if(!in_array($type,['CYCLE','FULL','SPOT','QUALITY_HOLD'],true))failRequest('El tipo de auditoría no es válido.',422);
    $pdo->prepare("INSERT INTO inventory_audit_schedules (schedule_name,warehouse_id,weekday_codes,start_time,count_type,scope_description,notes,is_active,created_by) VALUES (:name,:warehouse,:days,:time,:type,:scope,:notes,1,:user)")->execute(['name'=>requiredString($payload,'schedule_name','el nombre del programa',160),'warehouse'=>$warehouse['id'],'days'=>implode(',',$days),'time'=>$time.':00','type'=>$type,'scope'=>requiredString($payload,'scope_description','el alcance de la auditoría',255),'notes'=>optionalString($payload,'notes',1000),'user'=>$user['id']]);$id=(int)$pdo->lastInsertId();writeAudit($pdo,(int)$user['id'],'CREATE','inventory_audit_schedule',$id,['warehouse'=>$warehouse['name'],'weekdays'=>$days,'time'=>$time]);return ['id'=>$id,'warehouse'=>$warehouse['name'],'weekdays'=>$days];
}

function createArea(PDO $pdo, array $user, array $payload): array
{
    if(!isSuperAdmin($pdo,(int)$user['id'])) failRequest('Solo el administrador del sistema puede crear áreas.',403);
    $name=requiredString($payload,'area_name','el nombre del área',120);$code=uniqueGeneratedCode($pdo,'areas','code',$name);
    $pdo->prepare("INSERT INTO areas (code,name,is_active) VALUES (:code,:name,1)")->execute(['code'=>$code,'name'=>$name]);
    $id=(int)$pdo->lastInsertId();writeAudit($pdo,(int)$user['id'],'CREATE','area',$id,['name'=>$name]);return ['id'=>$id,'name'=>$name];
}

function createRole(PDO $pdo, array $user, array $payload): array
{
    if(!isSuperAdmin($pdo,(int)$user['id'])) failRequest('Solo el administrador del sistema puede crear roles.',403);
    $name=requiredString($payload,'role_name','el nombre del rol',100);$code=uniqueGeneratedCode($pdo,'roles','code',$name);
    $profile=(string)($payload['permission_profile']??'VIEWER');$profiles=['VIEWER'=>['VIEW','EXPORT'],'OPERATOR'=>['VIEW','CREATE','UPDATE','POST','EXPORT'],'APPROVER'=>['VIEW','APPROVE','REJECT','EXPORT'],'MANAGER'=>['VIEW','CREATE','UPDATE','APPROVE','REJECT','POST','EXPORT']];
    if(!isset($profiles[$profile])) failRequest('El nivel de permisos no es válido.',422);
    $modules=$payload['module_codes']??[];if(!is_array($modules))$modules=explode(',',(string)$modules);$modules=array_values(array_unique(array_filter(array_map(fn($x)=>strtoupper(trim((string)$x)),$modules))));if(!$modules)failRequest('Selecciona al menos un módulo.',422);
    $pdo->beginTransaction();$pdo->prepare("INSERT INTO roles (code,name,description,is_system,is_active) VALUES (:code,:name,:description,0,1)")->execute(['code'=>$code,'name'=>$name,'description'=>optionalString($payload,'description',255)]);$id=(int)$pdo->lastInsertId();
    $grant=$pdo->prepare("INSERT IGNORE INTO role_permissions (role_id,permission_id,granted_by) SELECT :role,p.id,:user FROM permissions p INNER JOIN app_modules m ON m.id=p.module_id WHERE m.code=:module AND p.action_code=:action");foreach($modules as $module){foreach($profiles[$profile] as $action)$grant->execute(['role'=>$id,'user'=>$user['id'],'module'=>$module,'action'=>$action]);}
    writeAudit($pdo,(int)$user['id'],'CREATE','role',$id,['name'=>$name,'modules'=>$modules,'profile'=>$profile]);$pdo->commit();return ['id'=>$id,'name'=>$name];
}

function createTechnician(PDO $pdo, array $user, array $payload): array
{
    $maintenanceArea=findOne($pdo,"SELECT id FROM areas WHERE code='MANTENIMIENTO' AND is_active=1",[],'No existe el área de Mantenimiento.');
    if(!isSuperAdmin($pdo,(int)$user['id']) && ((int)$user['primary_area_id']!==(int)$maintenanceArea['id'] || !isAreaLeader($pdo,(int)$user['id']))) failRequest('Solo el administrador de Mantenimiento puede registrar técnicos.',403);
    $payload['area_id']=$maintenanceArea['id'];$payload['role_code']='TECHNICIAN';$payload['module_codes']=['MAINTENANCE'];
    return createUser($pdo,$user,$payload);
}

function uniqueGeneratedCode(PDO $pdo, string $table, string $column, string $name): string
{
    $ascii=iconv('UTF-8','ASCII//TRANSLIT//IGNORE',$name)?:$name;$base=strtoupper(trim((string)preg_replace('/[^A-Za-z0-9]+/','_',$ascii),'_'));$base=substr($base?:'REGISTRO',0,32);$code=$base;$i=2;
    while((float)safeScalar($pdo,"SELECT COUNT(*) FROM {$table} WHERE {$column}=:code",['code'=>$code])>0){$suffix='_'.$i++;$code=substr($base,0,40-strlen($suffix)).$suffix;}
    return $code;
}

function createInitialInventory(PDO $pdo, array $user, array $payload): array
{
    requireArea($pdo,$user,['ALMACEN']);
    $warehouse=findOne($pdo,"SELECT id,name,warehouse_type FROM warehouses WHERE id=:id AND is_active=1",['id'=>(int)($payload['warehouse_id']??0)],'Selecciona un almacén válido.');
    $module=['RAW_MATERIAL'=>'WAREHOUSE_RAW','PACKAGING'=>'WAREHOUSE_PACKAGING','SPARE_PARTS'=>'WAREHOUSE_SPARES','FINISHED_GOODS'=>'WAREHOUSE_FINISHED'][$warehouse['warehouse_type']]??'INITIAL_INVENTORY';requireAnyPermissionV14($pdo,(int)$user['id'],[$module,'INITIAL_INVENTORY'],'POST');
    $date=validDate((string)($payload['inventory_date']??''));$lines=$payload['lines']??[];if(!is_array($lines)||!$lines||count($lines)>500)failRequest('Agrega entre 1 y 500 partidas al levantamiento.',422);
    $pdo->beginTransaction();
    try{
        $pdo->prepare("INSERT INTO initial_inventory_sessions (session_number,warehouse_id,inventory_date,status,notes,created_by) VALUES (:number,:warehouse,:date,'DRAFT',:notes,:user)")->execute(['number'=>provisionalNumber('LEV'),'warehouse'=>$warehouse['id'],'date'=>$date,'notes'=>optionalString($payload,'notes',1000),'user'=>$user['id']]);$sessionId=(int)$pdo->lastInsertId();$number=finalNumber('LEV',$sessionId);$pdo->prepare("UPDATE initial_inventory_sessions SET session_number=:number WHERE id=:id")->execute(['number'=>$number,'id'=>$sessionId]);
        $pdo->prepare("INSERT INTO inventory_movements (movement_number,movement_type,source_type,source_id,source_reference,status,movement_at,reason,created_by) VALUES (:number,'OTHER','initial_inventory_session',:source,:reference,'DRAFT',UTC_TIMESTAMP(6),'Carga de inventario inicial sin recepción de proveedor',:user)")->execute(['number'=>provisionalNumber('MOV'),'source'=>$sessionId,'reference'=>$number,'user'=>$user['id']]);$movementId=(int)$pdo->lastInsertId();$movementNumber=finalNumber('MOV',$movementId);$pdo->prepare("UPDATE inventory_movements SET movement_number=:number WHERE id=:id")->execute(['number'=>$movementNumber,'id'=>$movementId]);
        $insertSessionLine=$pdo->prepare("INSERT INTO initial_inventory_lines (initial_inventory_id,line_no,item_id,inventory_lot_id,location_id,uom_id,counted_qty,quality_status,notes) VALUES (:session,:line,:item,:lot,:location,:uom,:qty,:quality,:notes)");$insertMovement=$pdo->prepare("INSERT INTO inventory_movement_lines (movement_id,line_no,item_id,inventory_lot_id,warehouse_id,location_id,uom_id,quantity_delta,notes) VALUES (:movement,:line,:item,:lot,:warehouse,:location,:uom,:qty,:notes)");$seen=[];
        foreach(array_values($lines) as $index=>$line){if(!is_array($line))failRequest('Una partida del levantamiento no es válida.',422);$resolved=resolveInventoryCaptureLine($pdo,$warehouse,(array)$line,(int)$user['id'],$date,true);if($resolved['quantity']<=0)failRequest('La existencia inicial debe ser mayor que cero.',422);$dimension=$resolved['item_id'].'|'.($resolved['lot_id']??0).'|'.$resolved['location_id'];if(isset($seen[$dimension]))failRequest('Hay una partida repetida de '.$resolved['item_name'].' en la misma ubicación y lote.',422);$seen[$dimension]=true;$existing=safeScalar($pdo,"SELECT COALESCE(SUM(on_hand_qty),0) FROM vw_inventory_on_hand WHERE item_id=:item AND inventory_lot_id<=>:lot AND warehouse_id=:warehouse AND location_id=:location",['item'=>$resolved['item_id'],'lot'=>$resolved['lot_id'],'warehouse'=>$warehouse['id'],'location'=>$resolved['location_id']]);if(abs($existing)>0.000001)failRequest('Ya existe inventario para '.$resolved['item_name'].' en esa ubicación y lote. Usa una auditoría física para corregirlo.',409);$lineNo=$index+1;$params=['session'=>$sessionId,'line'=>$lineNo,'item'=>$resolved['item_id'],'lot'=>$resolved['lot_id'],'location'=>$resolved['location_id'],'uom'=>$resolved['uom_id'],'qty'=>$resolved['quantity'],'quality'=>$resolved['quality_status'],'notes'=>$resolved['notes']];$insertSessionLine->execute($params);$insertMovement->execute(['movement'=>$movementId,'line'=>$lineNo,'item'=>$resolved['item_id'],'lot'=>$resolved['lot_id'],'warehouse'=>$warehouse['id'],'location'=>$resolved['location_id'],'uom'=>$resolved['uom_id'],'qty'=>$resolved['quantity'],'notes'=>'Existencia inicial: '.$resolved['item_name']]);}
        postMovementV14($pdo,$movementId,(int)$user['id']);$pdo->prepare("UPDATE initial_inventory_sessions SET status='POSTED',movement_id=:movement,posted_by=:user,posted_at=UTC_TIMESTAMP(6) WHERE id=:id")->execute(['movement'=>$movementId,'user'=>$user['id'],'id'=>$sessionId]);writeAudit($pdo,(int)$user['id'],'CREATE','initial_inventory_session',$sessionId,['session_number'=>$number,'warehouse'=>$warehouse['name'],'lines'=>count($lines),'movement'=>$movementNumber]);$pdo->commit();return ['id'=>$sessionId,'number'=>$number,'movement'=>$movementNumber,'lines'=>count($lines)];
    }catch(Throwable $error){if($pdo->inTransaction())$pdo->rollBack();throw $error;}
}

function createPhysicalCount(PDO $pdo, array $user, array $payload): array
{
    requireArea($pdo,$user,['ALMACEN']);
    $warehouse=findOne($pdo,"SELECT id,name,warehouse_type FROM warehouses WHERE id=:id AND is_active=1",['id'=>(int)($payload['warehouse_id']??0)],'Selecciona un almacén válido.');$module=['RAW_MATERIAL'=>'WAREHOUSE_RAW','PACKAGING'=>'WAREHOUSE_PACKAGING','SPARE_PARTS'=>'WAREHOUSE_SPARES','FINISHED_GOODS'=>'WAREHOUSE_FINISHED'][$warehouse['warehouse_type']]??'COUNTS';requireAnyPermissionV14($pdo,(int)$user['id'],[$module,'COUNTS'],'APPROVE');$lines=$payload['lines']??[];if(!is_array($lines)||!$lines||count($lines)>500)failRequest('Agrega entre 1 y 500 partidas al conteo.',422);$date=validDate((string)($payload['inventory_date']??gmdate('Y-m-d')));
    $pdo->beginTransaction();try{$pdo->prepare("INSERT INTO inventory_counts (count_number,warehouse_id,count_type,status,freeze_at,started_at,completed_at,approved_by,approved_at,created_by) VALUES (:number,:warehouse,'SPOT','APPROVED',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6),UTC_TIMESTAMP(6),:approved_user,UTC_TIMESTAMP(6),:created_user)")->execute(['number'=>provisionalNumber('AUD'),'warehouse'=>$warehouse['id'],'approved_user'=>$user['id'],'created_user'=>$user['id']]);$countId=(int)$pdo->lastInsertId();$number=finalNumber('AUD',$countId);$pdo->prepare("UPDATE inventory_counts SET count_number=:number WHERE id=:id")->execute(['number'=>$number,'id'=>$countId]);
        $movementId=null;$movementNumber=null;$movementLine=0;$insertCount=$pdo->prepare("INSERT INTO inventory_count_lines (inventory_count_id,item_id,inventory_lot_id,location_id,system_qty,first_count_qty,final_count_qty,counted_by,notes) VALUES (:count,:item,:lot,:location,:system,:first_count,:final_count,:user,:notes)");$seen=[];
        foreach(array_values($lines) as $line){$resolved=resolveInventoryCaptureLine($pdo,$warehouse,(array)$line,(int)$user['id'],$date,false);$dimension=$resolved['item_id'].'|'.($resolved['lot_id']??0).'|'.$resolved['location_id'];if(isset($seen[$dimension]))failRequest('Hay una partida repetida de '.$resolved['item_name'].' en la misma ubicación y lote.',422);$seen[$dimension]=true;$system=(float)safeScalar($pdo,"SELECT COALESCE(SUM(on_hand_qty),0) FROM vw_inventory_on_hand WHERE item_id=:item AND inventory_lot_id<=>:lot AND warehouse_id=:warehouse AND location_id=:location",['item'=>$resolved['item_id'],'lot'=>$resolved['lot_id'],'warehouse'=>$warehouse['id'],'location'=>$resolved['location_id']]);$insertCount->execute(['count'=>$countId,'item'=>$resolved['item_id'],'lot'=>$resolved['lot_id'],'location'=>$resolved['location_id'],'system'=>$system,'first_count'=>$resolved['quantity'],'final_count'=>$resolved['quantity'],'user'=>$user['id'],'notes'=>$resolved['notes']]);$delta=$resolved['quantity']-$system;if(abs($delta)>0.000001){if($movementId===null){$pdo->prepare("INSERT INTO inventory_movements (movement_number,movement_type,source_type,source_id,source_reference,status,movement_at,reason,created_by) VALUES (:number,'COUNT_ADJUSTMENT','inventory_count',:source,:reference,'DRAFT',UTC_TIMESTAMP(6),'Ajuste aprobado por auditoría física',:user)")->execute(['number'=>provisionalNumber('MOV'),'source'=>$countId,'reference'=>$number,'user'=>$user['id']]);$movementId=(int)$pdo->lastInsertId();$movementNumber=finalNumber('MOV',$movementId);$pdo->prepare("UPDATE inventory_movements SET movement_number=:number WHERE id=:id")->execute(['number'=>$movementNumber,'id'=>$movementId]);}$movementLine++;$pdo->prepare("INSERT INTO inventory_movement_lines (movement_id,line_no,item_id,inventory_lot_id,warehouse_id,location_id,uom_id,quantity_delta,notes) VALUES (:movement,:line,:item,:lot,:warehouse,:location,:uom,:qty,:notes)")->execute(['movement'=>$movementId,'line'=>$movementLine,'item'=>$resolved['item_id'],'lot'=>$resolved['lot_id'],'warehouse'=>$warehouse['id'],'location'=>$resolved['location_id'],'uom'=>$resolved['uom_id'],'qty'=>$delta,'notes'=>'Diferencia de auditoría: '.$resolved['item_name']]);}}
        if($movementId!==null){$pdo->prepare("UPDATE inventory_counts SET adjustment_movement_id=:movement WHERE id=:id")->execute(['movement'=>$movementId,'id'=>$countId]);postMovementV14($pdo,$movementId,(int)$user['id']);}writeAudit($pdo,(int)$user['id'],'APPROVE','inventory_count',$countId,['count_number'=>$number,'lines'=>count($lines),'adjustments'=>$movementLine,'movement'=>$movementNumber]);$pdo->commit();return ['id'=>$countId,'number'=>$number,'movement'=>$movementNumber,'adjustments'=>$movementLine];
    }catch(Throwable $error){if($pdo->inTransaction())$pdo->rollBack();throw $error;}
}

function resolveInventoryCaptureLine(PDO $pdo, array $warehouse, array $line, int $userId, string $date, bool $allowCreateLot): array
{
    $item=findOne($pdo,"SELECT i.id,i.name,i.item_type,i.base_uom_id,i.lot_controlled,i.quality_required FROM items i WHERE i.id=:id AND i.is_active=1",['id'=>(int)($line['item_id']??0)],'Selecciona un producto o material válido.');$allowed=['RAW_MATERIAL'=>['RAW_FRUIT','RAW_OTHER','BULK_OIL'],'PACKAGING'=>['PACKAGING','CONSUMABLE'],'SPARE_PARTS'=>['SPARE_PART'],'FINISHED_GOODS'=>['FINISHED_GOOD']];if(isset($warehouse['warehouse_type'])&&!in_array($item['item_type'],$allowed[$warehouse['warehouse_type']]??[],true))failRequest('El producto o material no pertenece al almacén seleccionado.',422);$location=findOne($pdo,"SELECT id,location_type,is_blocked FROM warehouse_locations WHERE id=:id AND warehouse_id=:warehouse AND is_active=1",['id'=>(int)($line['location_id']??0),'warehouse'=>$warehouse['id']],'La ubicación no pertenece al almacén seleccionado.');$quantity=filter_var($line['quantity']??null,FILTER_VALIDATE_FLOAT);if($quantity===false||$quantity<0)failRequest('La cantidad física debe ser igual o mayor que cero.',422);$quality=strtoupper(trim((string)($line['quality_status']??'APPROVED')));if(!in_array($quality,['PENDING','APPROVED','CONDITIONAL','REJECTED'],true))failRequest('El estado de Calidad no es válido.',422);if((int)$location['is_blocked']===1&&!in_array($location['location_type'],['QUALITY_HOLD','REJECTED'],true))failRequest('La ubicación seleccionada está bloqueada.',409);if($quality==='REJECTED'&&$location['location_type']!=='REJECTED')failRequest('El producto rechazado debe capturarse en la zona de rechazados.',422);if($quality==='PENDING'&&!in_array($location['location_type'],['RECEIVING','QUALITY_HOLD'],true))failRequest('El producto pendiente de Calidad debe quedar en recepción temporal o pendiente de liberación.',422);if(in_array($quality,['APPROVED','CONDITIONAL'],true)&&!in_array($location['location_type'],['STORAGE','PICKING'],true))failRequest('El producto liberado debe quedar en existencia disponible o preparación de surtido.',422);$lotId=null;$lotCode=trim((string)($line['lot_code']??''));
    if((int)$item['lot_controlled']===1){if($lotCode==='')failRequest('Indica el lote de '.$item['name'].'.',422);$statement=$pdo->prepare("SELECT id FROM inventory_lots WHERE item_id=:item AND lot_code=:lot LIMIT 1");$statement->execute(['item'=>$item['id'],'lot'=>$lotCode]);$lotId=$statement->fetchColumn();if(!$lotId){if(!$allowCreateLot && $quantity<=0)failRequest('El lote indicado no existe.',422);$lotStatus=in_array($quality,['PENDING','REJECTED'],true)?'BLOCKED':'OPEN';$pdo->prepare("INSERT INTO inventory_lots (item_id,lot_code,received_date,quality_status,lot_status,created_by) VALUES (:item,:lot,:date,:quality,:status,:user)")->execute(['item'=>$item['id'],'lot'=>$lotCode,'date'=>$date,'quality'=>$quality,'status'=>$lotStatus,'user'=>$userId]);$lotId=(int)$pdo->lastInsertId();}}
    return ['item_id'=>(int)$item['id'],'item_name'=>$item['name'],'uom_id'=>(int)$item['base_uom_id'],'location_id'=>(int)$location['id'],'lot_id'=>$lotId===null?null:(int)$lotId,'quantity'=>(float)$quantity,'quality_status'=>(int)$item['lot_controlled']===1?$quality:null,'notes'=>mb_substr(trim((string)($line['notes']??'')),0,500)?:null];
}

function validDate(string $value): string
{
    $date=DateTimeImmutable::createFromFormat('!Y-m-d',$value,new DateTimeZone('America/Mexico_City'));if(!$date||$date->format('Y-m-d')!==$value)failRequest('La fecha no es válida.',422);return $value;
}

function importForecast(PDO $pdo, array $user, array $payload): array
{
    requireArea($pdo,$user,['PLANEACION']);
    requirePermission($pdo,(int)$user['id'],'FORECAST','CREATE');$rows=$payload['rows']??[];if(!is_array($rows)||!$rows||count($rows)>20000)failRequest('El archivo debe contener entre 1 y 20,000 registros.',422);$year=(int)($payload['fiscal_year']??0);if($year<2020||$year>2100)failRequest('El año del Forecast no es válido.',422);$normalized=[];$missing=[];$invalid=[];
    $findItem=$pdo->prepare("SELECT id,name FROM items WHERE sku=:code AND item_type='FINISHED_GOOD' AND is_active=1 LIMIT 1");$findCustomer=$pdo->prepare("SELECT id FROM customers WHERE customer_code=:customer_code OR legal_name=:legal_name OR trade_name=:trade_name LIMIT 1");
    foreach($rows as $index=>$row){if(!is_array($row))continue;$code=strtoupper(trim((string)($row['product_code']??'')));$period=(string)($row['period_start']??'');$qty=filter_var($row['quantity']??null,FILTER_VALIDATE_FLOAT);if($code===''||!preg_match('/^\d{4}-\d{2}-01$/',$period)||$qty===false||(float)$qty<0){$invalid[]=$index+1;continue;}$findItem->execute(['code'=>$code]);$item=$findItem->fetch();if(!$item){$missing[$code]=true;continue;}$customerId=null;$customer=trim((string)($row['customer']??''));if($customer!==''){$findCustomer->execute(['customer_code'=>$customer,'legal_name'=>$customer,'trade_name'=>$customer]);$customerId=$findCustomer->fetchColumn()?:null;}$key=$item['id'].'|'.($customerId??0).'|'.$period;if(!isset($normalized[$key]))$normalized[$key]=['item'=>(int)$item['id'],'customer'=>$customerId===null?null:(int)$customerId,'period'=>$period,'quantity'=>0,'source'=>$code.'-'.$period];$normalized[$key]['quantity']+=(float)$qty;}
    if($missing||$invalid)return ['imported'=>false,'matchedRows'=>count($normalized),'missingProductCodes'=>array_keys($missing),'invalidRows'=>array_slice($invalid,0,100)];
    $planCode='FORECAST-'.$year;$planName=trim((string)($payload['plan_name']??''))?:'Plan anual '.$year;$versionName=requiredString($payload,'version_name','el nombre de la versión',120);$reason=requiredString($payload,'change_reason','el motivo de la importación',1000);
    $pdo->beginTransaction();try{$pdo->prepare("INSERT INTO forecast_plans (plan_code,name,fiscal_year,status,created_by) VALUES (:code,:name,:year,'ACTIVE',:user) ON DUPLICATE KEY UPDATE name=VALUES(name)")->execute(['code'=>$planCode,'name'=>$planName,'year'=>$year,'user'=>$user['id']]);$plan=findOne($pdo,"SELECT id FROM forecast_plans WHERE plan_code=:code FOR UPDATE",['code'=>$planCode],'No se pudo crear el plan.');$versionNo=(int)safeScalar($pdo,"SELECT COALESCE(MAX(version_no),0)+1 FROM forecast_versions WHERE forecast_plan_id=:plan",['plan'=>$plan['id']]);$type=$versionNo===1?'ORIGINAL':'REVISION';$pdo->prepare("UPDATE forecast_versions SET is_current=0 WHERE forecast_plan_id=:plan AND is_current=1")->execute(['plan'=>$plan['id']]);$pdo->prepare("INSERT INTO forecast_versions (forecast_plan_id,version_no,version_type,version_name,source_file_name,source_file_hash,change_reason,is_current,approved_by,approved_at,imported_by) VALUES (:plan,:version,:type,:name,:file,:hash,:reason,1,:approved_user,UTC_TIMESTAMP(6),:imported_user)")->execute(['plan'=>$plan['id'],'version'=>$versionNo,'type'=>$type,'name'=>$versionName,'file'=>mb_substr((string)($payload['source_file_name']??''),0,255)?:null,'hash'=>preg_match('/^[a-f0-9]{64}$/',(string)($payload['source_file_hash']??''))?(string)$payload['source_file_hash']:null,'reason'=>$reason,'approved_user'=>$user['id'],'imported_user'=>$user['id']]);$versionId=(int)$pdo->lastInsertId();$insert=$pdo->prepare("INSERT INTO forecast_lines (forecast_version_id,customer_id,finished_item_id,period_start,forecast_qty,source_row_key) VALUES (:version,:customer,:item,:period,:quantity,:source)");foreach($normalized as $row)$insert->execute(['version'=>$versionId,'customer'=>$row['customer'],'item'=>$row['item'],'period'=>$row['period'],'quantity'=>$row['quantity'],'source'=>$row['source']]);if($versionNo>1){$planningArea=safeScalar($pdo,"SELECT id FROM areas WHERE code='PLANEACION' LIMIT 1");$pdo->prepare("INSERT IGNORE INTO alerts (alert_type,severity,title,message,entity_type,entity_id,area_id,status,deduplication_key) VALUES ('FORECAST_CHANGE','WARNING',:title,:message,'forecast_version',:entity,:area,'OPEN',:dedup)")->execute(['title'=>'Nueva revisión del Forecast','message'=>"Se importó la versión {$versionNo} de {$planCode}. Motivo: {$reason}",'entity'=>(string)$versionId,'area'=>$planningArea?:null,'dedup'=>'FORECAST_VERSION_'.$versionId]);}$mrp=recalculateMrpForForecast($pdo,$versionId,(int)$user['id']);writeAudit($pdo,(int)$user['id'],'CREATE','forecast_version',$versionId,['plan'=>$planCode,'version'=>$versionNo,'rows'=>count($normalized),'mrp_run'=>$mrp['runNumber']],$reason);$pdo->commit();return ['imported'=>true,'plan'=>$planCode,'version'=>$versionNo,'type'=>$type,'rows'=>count($normalized),'mrp'=>$mrp];}catch(Throwable $error){if($pdo->inTransaction())$pdo->rollBack();throw $error;}
}

function createBomComponent(PDO $pdo, array $user, array $payload): array
{
    requireArea($pdo,$user,['ENVASADO','PRODUCCION']);
    requireAnyPermissionV14($pdo,(int)$user['id'],['FILLING','PRODUCTION'],'CREATE');
    $output=findOne($pdo,"SELECT id,sku,name,base_uom_id FROM items WHERE id=:id AND item_type='FINISHED_GOOD' AND is_active=1",['id'=>(int)($payload['finished_item_id']??0)],'Selecciona un producto terminado válido.');
    $component=findOne($pdo,"SELECT id,sku,name,base_uom_id FROM items WHERE id=:id AND item_type<>'FINISHED_GOOD' AND item_type<>'SERVICE' AND is_active=1",['id'=>(int)($payload['component_item_id']??0)],'Selecciona un material o materia prima válido.');
    $outputQty=filter_var($payload['output_quantity']??null,FILTER_VALIDATE_FLOAT);$componentQty=filter_var($payload['component_quantity']??null,FILTER_VALIDATE_FLOAT);$scrap=filter_var($payload['scrap_percent']??0,FILTER_VALIDATE_FLOAT);
    if($outputQty===false||$outputQty<=0||$componentQty===false||$componentQty<=0||$scrap===false||$scrap<0||$scrap>100)failRequest('Las cantidades deben ser mayores que cero y la merma debe estar entre cero y cien.',422);
    $pdo->beginTransaction();
    try{
        $code='BOM-'.substr((string)$output['sku'],0,44).'-'.substr(hash('sha256',(string)$output['id']),0,8);$pdo->prepare("INSERT INTO bills_of_material (bom_code,output_item_id,name,is_active,created_by) VALUES (:code,:item,:name,1,:user) ON DUPLICATE KEY UPDATE name=VALUES(name),is_active=1")->execute(['code'=>$code,'item'=>$output['id'],'name'=>'Lista de materiales de '.$output['name'],'user'=>$user['id']]);$bom=findOne($pdo,"SELECT id FROM bills_of_material WHERE bom_code=:code FOR UPDATE",['code'=>$code],'No se pudo preparar la lista de materiales.');
        $versionRows=safeRows($pdo,"SELECT id FROM bom_versions WHERE bom_id=:bom AND status='ACTIVE' ORDER BY version_no DESC LIMIT 1",['bom'=>$bom['id']]);
        if($versionRows){$versionId=(int)$versionRows[0]['id'];$pdo->prepare("UPDATE bom_versions SET output_qty=:quantity,output_uom_id=:uom WHERE id=:id")->execute(['quantity'=>$outputQty,'uom'=>$output['base_uom_id'],'id'=>$versionId]);}
        else{$next=(int)safeScalar($pdo,"SELECT COALESCE(MAX(version_no),0)+1 FROM bom_versions WHERE bom_id=:bom",['bom'=>$bom['id']]);$pdo->prepare("INSERT INTO bom_versions (bom_id,version_no,output_qty,output_uom_id,effective_from,status,approved_by,approved_at) VALUES (:bom,:version,:quantity,:uom,UTC_DATE(),'ACTIVE',:user,UTC_TIMESTAMP(6))")->execute(['bom'=>$bom['id'],'version'=>$next,'quantity'=>$outputQty,'uom'=>$output['base_uom_id'],'user'=>$user['id']]);$versionId=(int)$pdo->lastInsertId();}
        $line=(int)safeScalar($pdo,"SELECT COALESCE(MAX(line_no),0)+1 FROM bom_components WHERE bom_version_id=:version",['version'=>$versionId]);$pdo->prepare("INSERT INTO bom_components (bom_version_id,line_no,component_item_id,component_uom_id,qty_per_output,scrap_pct,is_optional) VALUES (:version,:line,:component,:uom,:quantity,:scrap,0) ON DUPLICATE KEY UPDATE component_uom_id=VALUES(component_uom_id),qty_per_output=VALUES(qty_per_output),scrap_pct=VALUES(scrap_pct),is_optional=0")->execute(['version'=>$versionId,'line'=>$line,'component'=>$component['id'],'uom'=>$component['base_uom_id'],'quantity'=>$componentQty,'scrap'=>$scrap]);
        $runs=recalculateCurrentForecasts($pdo,(int)$user['id']);writeAudit($pdo,(int)$user['id'],'UPDATE','bill_of_material',$bom['id'],['finished_product'=>$output['sku'],'component'=>$component['sku'],'quantity'=>$componentQty,'output_quantity'=>$outputQty]);$pdo->commit();return ['id'=>(int)$bom['id'],'product'=>$output['name'],'component'=>$component['name'],'mrpRuns'=>$runs];
    }catch(Throwable $error){if($pdo->inTransaction())$pdo->rollBack();throw $error;}
}

function recalculateCurrentForecasts(PDO $pdo, int $userId): int
{
    $versions=safeRows($pdo,"SELECT id FROM forecast_versions WHERE is_current=1 ORDER BY id");foreach($versions as $version)recalculateMrpForForecast($pdo,(int)$version['id'],$userId);return count($versions);
}

function recalculateMrpForForecast(PDO $pdo, int $forecastVersionId, int $userId): array
{
    $horizon=findOne($pdo,"SELECT MIN(period_start) AS start_date,LAST_DAY(MAX(period_start)) AS end_date FROM forecast_lines WHERE forecast_version_id=:version",['version'=>$forecastVersionId],'El Forecast no contiene periodos válidos.');
    $insertRun=$pdo->prepare("INSERT INTO mrp_runs (run_number,forecast_version_id,horizon_start,horizon_end,status,parameters_json,started_at,created_by) VALUES (:number,:version,:start,:end,'RUNNING',JSON_OBJECT('source','automatico'),UTC_TIMESTAMP(6),:user)");$insertRun->execute(['number'=>provisionalNumber('MRP'),'version'=>$forecastVersionId,'start'=>$horizon['start_date'],'end'=>$horizon['end_date'],'user'=>$userId]);$runId=(int)$pdo->lastInsertId();$runNumber=finalNumber('MRP',$runId);$pdo->prepare("UPDATE mrp_runs SET run_number=:number WHERE id=:id")->execute(['number'=>$runNumber,'id'=>$runId]);
    $grossRows=safeRows($pdo,"SELECT bc.component_item_id AS item_id,fl.period_start,SUM((fl.forecast_qty/bv.output_qty)*bc.qty_per_output*(1+(bc.scrap_pct/100))) AS gross_requirement FROM forecast_lines fl INNER JOIN bills_of_material bom ON bom.output_item_id=fl.finished_item_id AND bom.is_active=1 INNER JOIN bom_versions bv ON bv.bom_id=bom.id AND bv.status='ACTIVE' AND bv.effective_from<=fl.period_start AND (bv.effective_to IS NULL OR bv.effective_to>=fl.period_start) INNER JOIN bom_components bc ON bc.bom_version_id=bv.id WHERE fl.forecast_version_id=:version GROUP BY bc.component_item_id,fl.period_start ORDER BY bc.component_item_id,fl.period_start",['version'=>$forecastVersionId]);
    $missing=safeRows($pdo,"SELECT DISTINCT i.sku,i.name FROM forecast_lines fl INNER JOIN items i ON i.id=fl.finished_item_id WHERE fl.forecast_version_id=:version AND NOT EXISTS(SELECT 1 FROM bills_of_material bom INNER JOIN bom_versions bv ON bv.bom_id=bom.id AND bv.status='ACTIVE' WHERE bom.output_item_id=fl.finished_item_id AND bom.is_active=1 AND bv.effective_from<=fl.period_start AND (bv.effective_to IS NULL OR bv.effective_to>=fl.period_start)) ORDER BY i.name",['version'=>$forecastVersionId]);
    $inventory=safeRows($pdo,"SELECT i.id,i.minimum_stock,COALESCE(si.lead_time_days,i.lead_time_days) AS lead_days,COALESCE(SUM(v.on_hand_qty),0) AS on_hand,COALESCE(SUM(v.reserved_qty),0) AS reserved FROM items i LEFT JOIN vw_inventory_availability v ON v.item_id=i.id LEFT JOIN (SELECT item_id,MAX(lead_time_days) AS lead_time_days FROM supplier_items WHERE is_active=1 AND is_preferred=1 GROUP BY item_id) si ON si.item_id=i.id GROUP BY i.id,i.minimum_stock,si.lead_time_days,i.lead_time_days");$balances=[];foreach($inventory as $row)$balances[(int)$row['id']]=['onHand'=>(float)$row['on_hand'],'reserved'=>(float)$row['reserved'],'safety'=>(float)$row['minimum_stock'],'lead'=>(int)$row['lead_days'],'projected'=>max(0,(float)$row['on_hand']-(float)$row['reserved'])];
    $insert=$pdo->prepare("INSERT INTO mrp_requirements (mrp_run_id,item_id,requirement_date,gross_requirement,on_hand_qty,reserved_qty,scheduled_receipts,safety_stock_qty,net_requirement,suggested_order_qty,suggested_order_date,status) VALUES (:run,:item,:date,:gross,:on_hand,:reserved,0,:safety,:net,:suggested,:order_date,:status)");
    foreach($grossRows as $row){$itemId=(int)$row['item_id'];$balance=$balances[$itemId]??['onHand'=>0.0,'reserved'=>0.0,'safety'=>0.0,'lead'=>0,'projected'=>0.0];$gross=(float)$row['gross_requirement'];$net=max(0,$gross+$balance['safety']-$balance['projected']);$orderDate=(new DateTimeImmutable((string)$row['period_start']))->modify('-'.$balance['lead'].' days')->format('Y-m-d');$status=$net>0.000001?'SHORTAGE':'COVERED';$insert->execute(['run'=>$runId,'item'=>$itemId,'date'=>$row['period_start'],'gross'=>$gross,'on_hand'=>max(0,$balance['onHand']),'reserved'=>max(0,$balance['reserved']),'safety'=>max(0,$balance['safety']),'net'=>$net,'suggested'=>$net,'order_date'=>$orderDate,'status'=>$status]);$balance['projected']=max(0,$balance['projected']+$net-$gross);$balances[$itemId]=$balance;}
    $pdo->prepare("UPDATE mrp_runs SET status='COMPLETED',completed_at=UTC_TIMESTAMP(6) WHERE id=:id")->execute(['id'=>$runId]);
    $pdo->prepare("UPDATE alerts SET status='RESOLVED',resolved_at=UTC_TIMESTAMP(6) WHERE alert_type='MRP_SHORTAGE' AND status IN ('OPEN','ACKNOWLEDGED') AND entity_type='mrp_run' AND entity_id IN (SELECT CAST(id AS CHAR) FROM mrp_runs WHERE forecast_version_id=:version AND id<>:run)")->execute(['version'=>$forecastVersionId,'run'=>$runId]);
    $pdo->prepare("INSERT IGNORE INTO alerts (alert_type,severity,title,message,entity_type,entity_id,area_id,status,deduplication_key) SELECT 'MRP_SHORTAGE','WARNING',CONCAT('Faltante: ',i.name),CONCAT('Se necesitan ',ROUND(r.net_requirement,3),' ',u.name,' para ',DATE_FORMAT(r.requirement_date,'%d/%m/%Y'),'. Código: ',i.sku),'mrp_run',CAST(r.mrp_run_id AS CHAR),a.id,'OPEN',CONCAT('MRP_',r.mrp_run_id,'_',r.item_id,'_',r.requirement_date,'_',a.code) FROM mrp_requirements r INNER JOIN items i ON i.id=r.item_id INNER JOIN units_of_measure u ON u.id=i.base_uom_id INNER JOIN areas a ON a.code IN ('COMPRAS','ALMACEN') WHERE r.mrp_run_id=:run AND r.status='SHORTAGE'")->execute(['run'=>$runId]);
    return ['runId'=>$runId,'runNumber'=>$runNumber,'requirements'=>count($grossRows),'missingBillsOfMaterial'=>$missing];
}

function createMaintenanceWorkRequest(PDO $pdo, array $user, array $payload, array $config): array
{
    requirePermission($pdo,(int)$user['id'],'MAINTENANCE','CREATE');$areaId=isSuperAdmin($pdo,(int)$user['id'])?(int)($payload['area_id']??$user['primary_area_id']):(int)$user['primary_area_id'];$area=findOne($pdo,"SELECT id,name FROM areas WHERE id=:id AND is_active=1",['id'=>$areaId],'El área solicitante no es válida.');$assetId=null;if((int)($payload['asset_id']??0)>0){$asset=findOne($pdo,"SELECT id FROM maintenance_assets WHERE id=:id AND is_active=1",['id'=>(int)$payload['asset_id']],'El equipo no existe.');$assetId=$asset['id'];}$priority=strtoupper((string)($payload['priority_code']??'NORMAL'));if(!in_array($priority,['LOW','NORMAL','HIGH','CRITICAL'],true))failRequest('La prioridad no es válida.',422);$needed=new DateTimeImmutable(requiredString($payload,'needed_at','la fecha requerida'),new DateTimeZone('America/Mexico_City'));
    $pdo->beginTransaction();$pdo->prepare("INSERT INTO maintenance_work_requests (request_number,title,description,asset_id,requesting_area_id,location_description,requested_materials,priority_code,needed_at,status,requested_by) VALUES (:number,:title,:description,:asset,:area,:location,:materials,:priority,:needed,'REQUESTED',:user)")->execute(['number'=>provisionalNumber('SOL'),'title'=>requiredString($payload,'title','el título',190),'description'=>requiredString($payload,'description','la descripción',3000),'asset'=>$assetId,'area'=>$area['id'],'location'=>optionalString($payload,'location_description',255),'materials'=>optionalString($payload,'requested_materials',2000),'priority'=>$priority,'needed'=>$needed->setTimezone(new DateTimeZone('UTC'))->format('Y-m-d H:i:s'),'user'=>$user['id']]);$id=(int)$pdo->lastInsertId();$number=finalNumber('SOL',$id);$pdo->prepare("UPDATE maintenance_work_requests SET request_number=:number WHERE id=:id")->execute(['number'=>$number,'id'=>$id]);writeAudit($pdo,(int)$user['id'],'CREATE','maintenance_work_request',$id,['request_number'=>$number,'area'=>$area['name'],'priority'=>$priority]);$pdo->commit();$recipients=notificationRecipients($pdo,['ALMACEN','MANTENIMIENTO']);queueNotifications($pdo,$config,'MAINTENANCE_REQUEST','maintenance_work_request',$id,$recipients,"Nueva solicitud de Mantenimiento {$number}","Se registró {$number}: ".trim((string)$payload['title']).". Área solicitante: {$area['name']}. Prioridad: {$priority}. Fecha requerida: ".$needed->format('d/m/Y H:i').'.');return ['id'=>$id,'number'=>$number,'notifications'=>count($recipients)];
}

function assignMaintenanceTechnicians(PDO $pdo, array $user, array $payload, array $config): array
{
    $request=findOne($pdo,"SELECT id,request_number,title FROM maintenance_work_requests WHERE id=:id",['id'=>(int)($payload['request_id']??0)],'La solicitud no existe.');if(!isMaintenanceLeader($pdo,$user))failRequest('Solo el administrador o jefe de Mantenimiento puede asignar técnicos.',403);$assignments=$payload['assignments']??[];if(!is_array($assignments)||!$assignments)failRequest('Selecciona al menos un técnico.',422);$pdo->beginTransaction();$assigned=[];foreach($assignments as $entry){$technician=findOne($pdo,"SELECT u.id,u.display_name,u.email FROM maintenance_technicians t INNER JOIN app_users u ON u.id=t.user_id WHERE u.id=:id AND t.is_active=1 AND u.status='ACTIVE'",['id'=>(int)($entry['technician_user_id']??0)],'Uno de los técnicos no está disponible.');$hours=filter_var($entry['estimated_hours']??null,FILTER_VALIDATE_FLOAT);if($hours===false||$hours<=0||$hours>999)failRequest('Las horas estimadas deben ser mayores que cero.',422);$pdo->prepare("INSERT INTO maintenance_work_assignments (work_request_id,technician_user_id,assigned_by,estimated_hours,assignment_status) VALUES (:request,:technician,:user,:hours,'ASSIGNED') ON DUPLICATE KEY UPDATE estimated_hours=VALUES(estimated_hours),assignment_status='ASSIGNED',assigned_by=VALUES(assigned_by),assigned_at=UTC_TIMESTAMP(6)")->execute(['request'=>$request['id'],'technician'=>$technician['id'],'user'=>$user['id'],'hours'=>$hours]);$assigned[]=['name'=>$technician['display_name'],'email'=>$technician['email'],'hours'=>$hours];}$pdo->prepare("UPDATE maintenance_work_requests SET status='ASSIGNED' WHERE id=:id AND status='REQUESTED'")->execute(['id'=>$request['id']]);writeAudit($pdo,(int)$user['id'],'UPDATE','maintenance_work_request',$request['id'],['assigned_technicians'=>array_column($assigned,'name')]);$pdo->commit();foreach($assigned as $technician)queueNotifications($pdo,$config,'MAINTENANCE_ASSIGNED','maintenance_work_request',$request['id'],[['email'=>$technician['email'],'name'=>$technician['name']]],"Tarea de Mantenimiento asignada {$request['request_number']}","Se te asignó la tarea {$request['request_number']}: {$request['title']}. Tiempo estimado: {$technician['hours']} horas. Consulta la aplicación para ver todos los datos y registrar tu intervención.");return ['id'=>(int)$request['id'],'assigned'=>count($assigned)];
}

function updateMaintenanceWork(PDO $pdo, array $user, array $payload, array $config): array
{
    $request=findOne($pdo,"SELECT id,request_number,title FROM maintenance_work_requests WHERE id=:id",['id'=>(int)($payload['request_id']??0)],'La solicitud no existe.');$leader=isMaintenanceLeader($pdo,$user);$assignmentRows=safeRows($pdo,"SELECT id FROM maintenance_work_assignments WHERE work_request_id=:request AND technician_user_id=:user AND assignment_status<>'CANCELLED' LIMIT 1",['request'=>$request['id'],'user'=>$user['id']]);if(!$leader&&!$assignmentRows)failRequest('Esta tarea no está asignada a tu usuario.',403);$assignmentId=$assignmentRows[0]['id']??null;$status=strtoupper((string)($payload['work_status']??''));if(!in_array($status,['IN_PROGRESS','WAITING_PARTS','COMPLETED','VERIFIED'],true))failRequest('El estado de la intervención no es válido.',422);if($status==='VERIFIED'&&!$leader)failRequest('Solo el jefe de Mantenimiento puede verificar el cierre.',403);$hours=filter_var($payload['hours_reported']??0,FILTER_VALIDATE_FLOAT);if($hours===false||$hours<0||$hours>999)failRequest('Las horas reportadas no son válidas.',422);$observations=requiredString($payload,'observations','las observaciones',3000);
    $pdo->beginTransaction();$pdo->prepare("INSERT INTO maintenance_work_updates (work_request_id,assignment_id,status,hours_reported,observations,updated_by) VALUES (:request,:assignment,:status,:hours,:observations,:user)")->execute(['request'=>$request['id'],'assignment'=>$assignmentId,'status'=>$status,'hours'=>$hours,'observations'=>$observations,'user'=>$user['id']]);if($assignmentId!==null){$assignmentStatus=$status==='WAITING_PARTS'?'IN_PROGRESS':$status;$pdo->prepare("UPDATE maintenance_work_assignments SET assignment_status=:status,actual_hours=actual_hours+:hours,work_notes=:notes,started_at=CASE WHEN :status2='IN_PROGRESS' THEN COALESCE(started_at,UTC_TIMESTAMP(6)) ELSE started_at END,completed_at=CASE WHEN :status3='COMPLETED' THEN UTC_TIMESTAMP(6) ELSE completed_at END WHERE id=:id")->execute(['status'=>$assignmentStatus,'hours'=>$hours,'notes'=>$observations,'status2'=>$assignmentStatus,'status3'=>$assignmentStatus,'id'=>$assignmentId]);}$requestStatus=$status;if($status==='COMPLETED'){$remaining=safeScalar($pdo,"SELECT COUNT(*) FROM maintenance_work_assignments WHERE work_request_id=:request AND assignment_status NOT IN ('COMPLETED','CANCELLED')",['request'=>$request['id']]);if($remaining>0)$requestStatus='IN_PROGRESS';}$pdo->prepare("UPDATE maintenance_work_requests SET status=:status,verified_by=CASE WHEN :verify='VERIFIED' THEN :user ELSE verified_by END,verified_at=CASE WHEN :verify2='VERIFIED' THEN UTC_TIMESTAMP(6) ELSE verified_at END WHERE id=:id")->execute(['status'=>$requestStatus,'verify'=>$status,'user'=>$user['id'],'verify2'=>$status,'id'=>$request['id']]);writeAudit($pdo,(int)$user['id'],'UPDATE','maintenance_work_request',$request['id'],['status'=>$requestStatus,'hours'=>$hours],$observations);$pdo->commit();$recipients=notificationRecipients($pdo,['MANTENIMIENTO','ALMACEN']);queueNotifications($pdo,$config,'MAINTENANCE_UPDATED','maintenance_work_request',$request['id'],$recipients,"Actualización de Mantenimiento {$request['request_number']}","La tarea {$request['request_number']} cambió a {$requestStatus}. Horas registradas: {$hours}. Observaciones: {$observations}");return ['id'=>(int)$request['id'],'status'=>$requestStatus];
}

function isMaintenanceLeader(PDO $pdo, array $user): bool
{
    if(isSuperAdmin($pdo,(int)$user['id']))return true;$statement=$pdo->prepare("SELECT 1 FROM areas a WHERE a.id=:area AND a.code='MANTENIMIENTO'");$statement->execute(['area'=>$user['primary_area_id']]);return (bool)$statement->fetchColumn()&&isAreaLeader($pdo,(int)$user['id']);
}

function notificationRecipients(PDO $pdo, array $areaCodes): array
{
    $marks=implode(',',array_fill(0,count($areaCodes),'?'));$statement=$pdo->prepare("SELECT DISTINCT u.email,u.display_name AS name FROM app_users u INNER JOIN areas a ON a.id=u.primary_area_id INNER JOIN user_roles ur ON ur.user_id=u.id AND ur.is_active=1 INNER JOIN roles r ON r.id=ur.role_id WHERE u.status='ACTIVE' AND a.code IN ({$marks}) AND r.code IN ('AREA_ADMIN','AREA_MANAGER','SUPER_ADMIN')");$statement->execute($areaCodes);$rows=$statement->fetchAll()?:[];if(!$rows)$rows=safeRows($pdo,"SELECT u.email,u.display_name AS name FROM app_users u INNER JOIN user_roles ur ON ur.user_id=u.id AND ur.is_active=1 INNER JOIN roles r ON r.id=ur.role_id WHERE r.code='SUPER_ADMIN' AND u.status='ACTIVE' LIMIT 1");return $rows;
}

function queueNotifications(PDO $pdo, array $config, string $event, string $entity, int $entityId, array $recipients, string $subject, string $body): void
{
    $enabled=(bool)($config['notifications']['enabled']??true);$from=(string)($config['notifications']['from_email']??'notificaciones@ci4kash.com');$fromName=(string)($config['notifications']['from_name']??'Oleolab');foreach($recipients as $recipient){$email=trim((string)($recipient['email']??''));if(!filter_var($email,FILTER_VALIDATE_EMAIL))continue;$pdo->prepare("INSERT INTO email_notifications (event_type,entity_type,entity_id,recipient_email,recipient_name,subject_line,delivery_status) VALUES (:event,:entity,:entity_id,:email,:name,:subject,'QUEUED')")->execute(['event'=>$event,'entity'=>$entity,'entity_id'=>(string)$entityId,'email'=>$email,'name'=>$recipient['name']??null,'subject'=>mb_substr($subject,0,255)]);$id=(int)$pdo->lastInsertId();if(!$enabled){$pdo->prepare("UPDATE email_notifications SET delivery_status='SKIPPED',error_message='Notificaciones desactivadas en la configuración' WHERE id=:id")->execute(['id'=>$id]);continue;}$headers=['MIME-Version: 1.0','Content-Type: text/plain; charset=UTF-8','From: '.$fromName.' <'.$from.'>','X-Mailer: Oleolab Almacenes'];$sent=@mail($email,$subject,$body,implode("\r\n",$headers));$pdo->prepare("UPDATE email_notifications SET delivery_status=:status,sent_at=CASE WHEN :sent=1 THEN UTC_TIMESTAMP(6) ELSE NULL END,error_message=:error WHERE id=:id")->execute(['status'=>$sent?'SENT':'FAILED','sent'=>$sent?1:0,'error'=>$sent?null:'El servidor no confirmó la entrega mediante mail()','id'=>$id]);}
}

function uploadMaintenanceEvidence(PDO $pdo, array $user): never
{
    requirePermission($pdo,(int)$user['id'],'MAINTENANCE','UPDATE');$requestId=(int)($_POST['request_id']??0);$request=findOne($pdo,"SELECT id,requested_by FROM maintenance_work_requests WHERE id=:id",['id'=>$requestId],'La solicitud no existe.');$isRequester=(int)$request['requested_by']===(int)$user['id'];if(!isMaintenanceLeader($pdo,$user)&&!$isRequester&&safeScalar($pdo,"SELECT COUNT(*) FROM maintenance_work_assignments WHERE work_request_id=:request AND technician_user_id=:user AND assignment_status<>'CANCELLED'",['request'=>$requestId,'user'=>$user['id']])<1)failRequest('No puedes agregar evidencia a esta tarea.',403);if(!isset($_FILES['evidence'])||!is_uploaded_file($_FILES['evidence']['tmp_name']))failRequest('Selecciona una fotografía.',422);$file=$_FILES['evidence'];if((int)$file['size']<=0||(int)$file['size']>5*1024*1024)failRequest('Cada fotografía debe pesar menos de 5 MB.',413);$finfo=new finfo(FILEINFO_MIME_TYPE);$mime=$finfo->file($file['tmp_name']);$extensions=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];if(!isset($extensions[$mime]))failRequest('Solo se permiten fotografías JPG, PNG o WebP.',422);$directory=dirname(__DIR__).'/storage/private/maintenance';if(!is_dir($directory)&&!mkdir($directory,0750,true)&&!is_dir($directory))failRequest('No fue posible preparar el almacenamiento de evidencias.',500);$storageName=bin2hex(random_bytes(24)).'.'.$extensions[$mime];$destination=$directory.'/'.$storageName;if(!move_uploaded_file($file['tmp_name'],$destination))failRequest('No fue posible guardar la fotografía.',500);$hash=hash_file('sha256',$destination);$original=mb_substr((string)$file['name'],0,255);$pdo->prepare("INSERT INTO file_attachments (entity_type,entity_id,file_name,storage_key,mime_type,file_size_bytes,sha256_hash,uploaded_by) VALUES ('maintenance_work_request',:entity,:name,:key,:mime,:size,:hash,:user)")->execute(['entity'=>(string)$request['id'],'name'=>$original,'key'=>'storage/private/maintenance/'.$storageName,'mime'=>$mime,'size'=>$file['size'],'hash'=>$hash,'user'=>$user['id']]);$id=(int)$pdo->lastInsertId();writeAudit($pdo,(int)$user['id'],'CREATE','maintenance_evidence',$id,['work_request_id'=>$request['id'],'file_name'=>$original]);sendData(['id'=>$id,'fileName'=>$original],201);
}

function streamMaintenanceEvidence(PDO $pdo, array $user, int $evidenceId): never
{
    requirePermission($pdo,(int)$user['id'],'MAINTENANCE','VIEW');$evidence=findOne($pdo,"SELECT f.id,f.entity_id,f.file_name,f.storage_key,f.mime_type,f.file_size_bytes FROM file_attachments f WHERE f.id=:id AND f.entity_type='maintenance_work_request'",['id'=>$evidenceId],'La evidencia no existe.');$requestId=(int)$evidence['entity_id'];$canSee=isSuperAdmin($pdo,(int)$user['id'])||isMaintenanceLeader($pdo,$user)||(isAreaLeader($pdo,(int)$user['id'])&&safeScalar($pdo,"SELECT COUNT(*) FROM maintenance_work_requests WHERE id=:request AND requesting_area_id=:area",['request'=>$requestId,'area'=>$user['primary_area_id']])>0)||safeScalar($pdo,"SELECT COUNT(*) FROM maintenance_work_requests r WHERE r.id=:request AND (r.requested_by=:user OR EXISTS(SELECT 1 FROM maintenance_work_assignments a WHERE a.work_request_id=r.id AND a.technician_user_id=:technician AND a.assignment_status<>'CANCELLED'))",['request'=>$requestId,'user'=>$user['id'],'technician'=>$user['id']])>0;if(!$canSee)failRequest('No puedes consultar esta evidencia.',403);$path=dirname(__DIR__).'/'.ltrim((string)$evidence['storage_key'],'/');if(!is_file($path)){http_response_code(404);exit;}header('Content-Type: '.($evidence['mime_type']?:'application/octet-stream'));header('Content-Length: '.filesize($path));header('Content-Disposition: inline; filename="'.str_replace(['"',"\r","\n"],'',(string)$evidence['file_name']).'"');readfile($path);exit;
}
