<?php
declare(strict_types=1);

/** Funciones de la reingeniería del núcleo (migración 008). */

function tableExistsV18(PDO $pdo, string $table): bool
{
    $statement=$pdo->prepare("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=:table");
    $statement->execute(['table'=>$table]);
    return (int)$statement->fetchColumn() > 0;
}

function buildV18Lookups(PDO $pdo, array $user, bool $isAdmin): array
{
    if(!tableExistsV18($pdo,'finished_product_bom_assignments'))return [];
    $userId=(int)$user['id'];
    $canBom=$isAdmin||userHasPermission($pdo,$userId,'BOM_MANAGEMENT','VIEW');
    $canProduction=$isAdmin||userHasPermission($pdo,$userId,'PRODUCTION','VIEW');
    $canArrivals=$isAdmin||userHasPermission($pdo,$userId,'PLANNED_ARRIVALS','VIEW')||userHasPermission($pdo,$userId,'PURCHASING','VIEW');
    return [
        'finishedProductsV18'=>($canBom||$canProduction)?safeRows($pdo,"SELECT i.id,i.sku,i.name,p.presentation_ml AS presentationMl,COALESCE(a.assignment_status,'PENDING_FORMULATION') AS assignmentStatus,a.id AS assignmentId,a.compiled_bom_version_id AS compiledBomVersionId FROM items i INNER JOIN product_presentations p ON p.finished_item_id=i.id LEFT JOIN finished_product_bom_assignments a ON a.finished_item_id=i.id AND a.effective_to IS NULL WHERE i.item_type='FINISHED_GOOD' AND i.is_active=1 ORDER BY i.name"):[],
        'oilFormulaVersionsV18'=>$canBom?safeRows($pdo,"SELECT v.id,f.formulation_code AS code,f.name, v.version_no AS versionNo,DATE_FORMAT(v.effective_from,'%Y-%m-%d') AS effectiveFrom,GROUP_CONCAT(CONCAT(i.name,' ',FORMAT(c.percentage,3),'%') ORDER BY c.line_no SEPARATOR ' · ') AS components FROM oil_formulation_versions v INNER JOIN oil_formulations f ON f.id=v.oil_formulation_id INNER JOIN oil_formulation_components c ON c.oil_formulation_version_id=v.id INNER JOIN items i ON i.id=c.raw_item_id WHERE f.is_active=1 AND v.status='ACTIVE' GROUP BY v.id,f.formulation_code,f.name,v.version_no,v.effective_from ORDER BY f.name,v.version_no DESC"):[],
        'packagingItemsV18'=>$canBom?safeRows($pdo,"SELECT i.id,i.sku,i.name,i.base_uom_id AS uomId,u.code AS uom FROM items i INNER JOIN units_of_measure u ON u.id=i.base_uom_id WHERE i.item_type='PACKAGING' AND i.is_active=1 ORDER BY i.name"):[],
        'plannedArrivalItemsV18'=>$canArrivals?safeRows($pdo,"SELECT i.id,i.sku,i.name,i.item_type AS itemType,i.base_uom_id AS uomId,u.code AS uom,w.id AS warehouseId,w.name AS warehouse FROM items i INNER JOIN units_of_measure u ON u.id=i.base_uom_id INNER JOIN warehouses w ON w.is_active=1 AND w.warehouse_type=CASE WHEN i.item_type IN ('RAW_FRUIT','RAW_OTHER','BULK_OIL') THEN 'RAW_MATERIAL' WHEN i.item_type='PACKAGING' THEN 'PACKAGING' WHEN i.item_type='FINISHED_GOOD' THEN 'FINISHED_GOODS' ELSE 'NONE' END WHERE i.is_active=1 AND i.item_type IN ('RAW_FRUIT','RAW_OTHER','BULK_OIL','PACKAGING','FINISHED_GOOD') ORDER BY w.name,i.name"):[],
    ];
}

function buildV18Bootstrap(PDO $pdo, array $user, bool $isAdmin): array
{
    $empty=['coreInventory'=>[],'weeklyForecast'=>[],'weeklyMaterialNeeds'=>[],'bomAssignments'=>[],'oilFormulations'=>[],'initialInventorySettings'=>[],'plannedArrivals'=>[],'sourceImportIssues'=>[]];
    if(!tableExistsV18($pdo,'finished_product_bom_assignments'))return $empty;
    $userId=(int)$user['id'];
    $canStock=$isAdmin||hasAnyPermissionV14($pdo,$userId,['WAREHOUSE_RAW','WAREHOUSE_PACKAGING','WAREHOUSE_FINISHED','INVENTORY'],'VIEW');
    $canForecast=$isAdmin||hasAnyPermissionV14($pdo,$userId,['FORECAST','MRP','PRODUCTION'],'VIEW');
    $canNeeds=$isAdmin||userHasPermission($pdo,$userId,'MRP','VIEW');
    $canBom=$isAdmin||userHasPermission($pdo,$userId,'BOM_MANAGEMENT','VIEW');
    $canArrivals=$isAdmin||hasAnyPermissionV14($pdo,$userId,['PLANNED_ARRIVALS','PURCHASING'],'VIEW');
    $inventory=$canStock?safeRows($pdo,"SELECT i.id AS itemId,i.sku,i.name,i.item_type AS itemType,w.code AS warehouseCode,w.name AS warehouse,u.code AS uom,COALESCE(SUM(CASE WHEN l.location_type IN ('STORAGE','PICKING','SHIPPING') AND l.is_blocked=0 THEN h.on_hand_qty ELSE 0 END),0) AS availableQty,COALESCE(SUM(CASE WHEN l.location_type IN ('QUALITY_HOLD','RECEIVING') THEN h.on_hand_qty ELSE 0 END),0) AS widQty,COALESCE(SUM(CASE WHEN l.location_type='REJECTED' THEN h.on_hand_qty ELSE 0 END),0) AS rejectedQty,COALESCE(SUM(h.on_hand_qty),0) AS totalQty FROM items i INNER JOIN units_of_measure u ON u.id=i.base_uom_id INNER JOIN warehouses w ON w.is_active=1 AND w.warehouse_type=CASE WHEN i.item_type IN ('RAW_FRUIT','RAW_OTHER','BULK_OIL') THEN 'RAW_MATERIAL' WHEN i.item_type='PACKAGING' THEN 'PACKAGING' WHEN i.item_type='FINISHED_GOOD' THEN 'FINISHED_GOODS' ELSE 'NONE' END LEFT JOIN vw_inventory_on_hand h ON h.item_id=i.id AND h.warehouse_id=w.id LEFT JOIN warehouse_locations l ON l.id=h.location_id WHERE i.is_active=1 AND i.item_type IN ('RAW_FRUIT','RAW_OTHER','BULK_OIL','PACKAGING','FINISHED_GOOD') GROUP BY i.id,i.sku,i.name,i.item_type,w.code,w.name,u.code ORDER BY w.name,i.name"):[];
    $weekly=$canForecast?safeRows($pdo,"SELECT f.week_start AS weekStart,i.id AS itemId,i.sku,i.name,SUM(f.forecast_qty) AS forecastQty,COALESCE(MAX(o.planned_qty),0) AS orderedQty FROM forecast_weekly_lines f INNER JOIN forecast_versions v ON v.id=f.forecast_version_id AND v.is_current=1 INNER JOIN items i ON i.id=f.finished_item_id LEFT JOIN (SELECT finished_item_id,DATE_SUB(DATE(planned_start),INTERVAL WEEKDAY(DATE(planned_start)) DAY) AS week_start,SUM(planned_qty) AS planned_qty FROM production_orders WHERE status<>'CANCELLED' GROUP BY finished_item_id,DATE_SUB(DATE(planned_start),INTERVAL WEEKDAY(DATE(planned_start)) DAY)) o ON o.finished_item_id=f.finished_item_id AND o.week_start=f.week_start GROUP BY f.week_start,i.id,i.sku,i.name ORDER BY f.week_start,i.name LIMIT 10000"):[];
    $needs=$canNeeds?weeklyNeedsV18($pdo):[];
    return [
        'coreInventory'=>$inventory,
        'weeklyForecast'=>$weekly,
        'weeklyMaterialNeeds'=>$needs,
        'bomAssignments'=>$canBom?safeRows($pdo,"SELECT a.id,i.id AS itemId,i.sku,i.name,p.presentation_ml AS presentationMl,a.assignment_status AS status,DATE_FORMAT(a.effective_from,'%Y-%m-%d') AS effectiveFrom,DATE_FORMAT(a.effective_to,'%Y-%m-%d') AS effectiveTo,bv.id AS packagingVersionId,COUNT(DISTINCT bc.id) AS packagingComponents,ofm.name AS oilFormula,ofv.id AS oilFormulaVersionId,ofv.version_no AS oilFormulaVersion,a.compiled_bom_version_id AS compiledBomVersionId,a.change_reason AS changeReason FROM finished_product_bom_assignments a INNER JOIN items i ON i.id=a.finished_item_id INNER JOIN product_presentations p ON p.finished_item_id=i.id INNER JOIN bom_versions bv ON bv.id=a.packaging_bom_version_id LEFT JOIN bom_components bc ON bc.bom_version_id=bv.id LEFT JOIN oil_formulation_versions ofv ON ofv.id=a.oil_formula_version_id LEFT JOIN oil_formulations ofm ON ofm.id=ofv.oil_formulation_id GROUP BY a.id,i.id,i.sku,i.name,p.presentation_ml,a.assignment_status,a.effective_from,a.effective_to,bv.id,ofm.name,ofv.id,ofv.version_no,a.compiled_bom_version_id,a.change_reason ORDER BY i.name,a.effective_from DESC"):[],
        'oilFormulations'=>$canBom?safeRows($pdo,"SELECT f.formulation_code AS code,f.name,v.id AS versionId,v.version_no AS versionNo,DATE_FORMAT(v.effective_from,'%Y-%m-%d') AS effectiveFrom,i.sku AS componentSku,i.name AS component,c.percentage,u.code AS uom FROM oil_formulations f INNER JOIN oil_formulation_versions v ON v.oil_formulation_id=f.id INNER JOIN oil_formulation_components c ON c.oil_formulation_version_id=v.id INNER JOIN items i ON i.id=c.raw_item_id INNER JOIN units_of_measure u ON u.id=i.base_uom_id WHERE f.is_active=1 ORDER BY f.name,v.version_no,c.line_no"):[],
        'initialInventorySettings'=>$canStock?safeRows($pdo,"SELECT w.id AS warehouseId,w.code,w.name,w.warehouse_type AS warehouseType,s.initial_capture_enabled AS enabled,DATE_FORMAT(s.disabled_at,'%d/%m/%Y %H:%i') AS disabledAt,COALESCE(u.display_name,'') AS disabledBy FROM warehouse_inventory_settings s INNER JOIN warehouses w ON w.id=s.warehouse_id LEFT JOIN app_users u ON u.id=s.disabled_by ORDER BY w.name"):[],
        'plannedArrivals'=>$canArrivals?safeRows($pdo,"SELECT a.id,a.arrival_number AS number,a.planned_week AS plannedWeek,i.sku,i.name AS item,a.expected_qty AS expectedQty,u.code AS uom,w.name AS warehouse,COALESCE(s.trade_name,s.legal_name,'Sin proveedor') AS supplier,a.status,a.notes FROM planned_material_arrivals a INNER JOIN items i ON i.id=a.item_id INNER JOIN units_of_measure u ON u.id=a.uom_id INNER JOIN warehouses w ON w.id=a.warehouse_id LEFT JOIN suppliers s ON s.id=a.supplier_id ORDER BY a.planned_week,a.id LIMIT 3000"):[],
        'sourceImportIssues'=>$isAdmin?safeRows($pdo,"SELECT severity,issue_code AS issueCode,entity_code AS entityCode,source_row AS sourceRow,message,is_resolved AS resolved FROM source_import_issues ORDER BY is_resolved,severity='ERROR' DESC,id LIMIT 1000"):[],
    ];
}

function weeklyNeedsV18(PDO $pdo): array
{
    $rows=safeRows($pdo,"SELECT requirement.weekStart,requirement.itemId,i.sku,i.name,i.item_type AS itemType,u.code AS uom,SUM(requirement.requiredQty) AS requiredQty FROM (SELECT f.week_start AS weekStart,bc.component_item_id AS itemId,SUM(f.forecast_qty*bc.qty_per_output/bv.output_qty*(1+bc.scrap_pct/100)) AS requiredQty FROM forecast_weekly_lines f INNER JOIN forecast_versions fv ON fv.id=f.forecast_version_id AND fv.is_current=1 INNER JOIN finished_product_bom_assignments a ON a.finished_item_id=f.finished_item_id AND a.effective_from<=f.week_start AND (a.effective_to IS NULL OR a.effective_to>=f.week_start) INNER JOIN bom_versions bv ON bv.id=a.packaging_bom_version_id INNER JOIN bom_components bc ON bc.bom_version_id=bv.id GROUP BY f.week_start,bc.component_item_id UNION ALL SELECT f.week_start,c.raw_item_id,SUM(f.forecast_qty*p.presentation_ml/1000*c.percentage/100) FROM forecast_weekly_lines f INNER JOIN forecast_versions fv ON fv.id=f.forecast_version_id AND fv.is_current=1 INNER JOIN product_presentations p ON p.finished_item_id=f.finished_item_id INNER JOIN finished_product_bom_assignments a ON a.finished_item_id=f.finished_item_id AND a.assignment_status='ACTIVE' AND a.effective_from<=f.week_start AND (a.effective_to IS NULL OR a.effective_to>=f.week_start) INNER JOIN oil_formulation_components c ON c.oil_formulation_version_id=a.oil_formula_version_id GROUP BY f.week_start,c.raw_item_id) requirement INNER JOIN items i ON i.id=requirement.itemId INNER JOIN units_of_measure u ON u.id=i.base_uom_id GROUP BY requirement.weekStart,requirement.itemId,i.sku,i.name,i.item_type,u.code ORDER BY requirement.itemId,requirement.weekStart");
    $stockRows=safeRows($pdo,"SELECT i.id AS itemId,COALESCE(SUM(a.available_qty),0) AS availableQty FROM items i LEFT JOIN vw_inventory_availability a ON a.item_id=i.id GROUP BY i.id");
    $arrivalRows=safeRows($pdo,"SELECT item_id AS itemId,planned_week AS weekStart,SUM(expected_qty) AS arrivingQty FROM planned_material_arrivals WHERE status IN ('PLANNED','NOTIFIED','APPOINTMENT_CREATED') GROUP BY item_id,planned_week");
    $stock=[];foreach($stockRows as $row)$stock[(int)$row['itemId']]=(float)$row['availableQty'];
    $arrivals=[];foreach($arrivalRows as $row)$arrivals[(int)$row['itemId'].'|'.$row['weekStart']]=(float)$row['arrivingQty'];
    $balances=[];$result=[];
    foreach($rows as $row){$item=(int)$row['itemId'];if(!array_key_exists($item,$balances))$balances[$item]=$stock[$item]??0.0;$arriving=$arrivals[$item.'|'.$row['weekStart']]??0.0;$start=$balances[$item];$required=(float)$row['requiredQty'];$end=$start+$arriving-$required;$balances[$item]=$end;$row['startingQty']=$start;$row['arrivingQty']=$arriving;$row['projectedQty']=$end;$row['shortageQty']=max(0,-$end);$result[]=$row;}
    return $result;
}

function createWarehouseMovementV18(PDO $pdo,array $user,array $payload,array $config): array
{
    requireArea($pdo,$user,['ALMACEN']);
    $direction=strtoupper(requiredString($payload,'movement_direction','el tipo de movimiento',10));
    if(!in_array($direction,['ENTRY','EXIT'],true))failRequest('Selecciona entrada o salida.',422);
    $warehouseType=strtoupper(trim((string)($payload['warehouse_type']??'')));
    $allowedWarehouseTypes=['RAW_MATERIAL','PACKAGING','SPARE_PARTS','FINISHED_GOODS'];
    if($warehouseType!==''&&!in_array($warehouseType,$allowedWarehouseTypes,true))failRequest('El almacén seleccionado no es válido.',422);
    $notes=requiredString($payload,'notes','el motivo u observación',500);

    if($direction==='ENTRY'){
        $item=findOne($pdo,"SELECT i.id,i.sku,i.name,i.item_type,i.base_uom_id,i.lot_controlled,i.quality_required,u.code AS uom_code,u.decimal_places,CASE WHEN i.item_type IN ('RAW_FRUIT','RAW_OTHER','BULK_OIL') THEN 'RAW_MATERIAL' WHEN i.item_type='PACKAGING' THEN 'PACKAGING' WHEN i.item_type='SPARE_PART' THEN 'SPARE_PARTS' WHEN i.item_type='FINISHED_GOOD' THEN 'FINISHED_GOODS' ELSE 'NONE' END AS warehouse_type FROM items i INNER JOIN units_of_measure u ON u.id=i.base_uom_id WHERE i.id=:item AND i.is_active=1",['item'=>(int)($payload['item_id']??0)],'Selecciona un producto o material activo.');
        if($item['warehouse_type']==='NONE')failRequest('Ese registro no corresponde a un almacén operativo.',422);
        if($warehouseType!==''&&$warehouseType!==$item['warehouse_type'])failRequest('El material no pertenece a este almacén.',422);
        if($item['item_type']==='FINISHED_GOOD')failRequest('La entrada de producto terminado se registra desde una orden de producción o desde la carga inicial autorizada.',422);
        $module=itemModuleV14((string)$item['item_type']);
        requireAnyPermissionV14($pdo,(int)$user['id'],[$module,'INVENTORY'],'POST');
        $warehouse=findOne($pdo,"SELECT id,name FROM warehouses WHERE is_active=1 AND code=CASE :code_type WHEN 'RAW_MATERIAL' THEN 'MP' WHEN 'PACKAGING' THEN 'EMPAQUE' WHEN 'SPARE_PARTS' THEN 'REF' ELSE '' END AND warehouse_type=:warehouse_type LIMIT 1",['code_type'=>$item['warehouse_type'],'warehouse_type'=>$item['warehouse_type']],'No se encontró el almacén oficial del material. Importa primero la migración 008.');
        $location=findOne($pdo,"SELECT id FROM warehouse_locations WHERE warehouse_id=:warehouse AND location_type='QUALITY_HOLD' AND is_active=1 ORDER BY id LIMIT 1",['warehouse'=>$warehouse['id']],'Falta la ubicación automática Pendiente de Calidad (WID). Importa nuevamente la migración 008.');
        $quantity=positiveNumber($payload,'quantity','La cantidad');
        if((int)$item['decimal_places']===0&&abs($quantity-round($quantity))>0.000001)failRequest('La unidad de este material sólo admite cantidades enteras.',422);
        $lotCode=masterCode($payload,'lot_code','el lote',100);
        if(safeScalar($pdo,"SELECT COUNT(*) FROM inventory_lots WHERE item_id=:item AND lot_code=:lot",['item'=>$item['id'],'lot'=>$lotCode])>0)failRequest('Ese lote ya existe para el material. Para corregir una existencia utiliza una auditoría física.',409);
        $reference=optionalString($payload,'reference',100);
        $pdo->beginTransaction();
        try{
            $pdo->prepare("INSERT INTO inventory_lots (item_id,lot_code,received_date,quality_status,lot_status,attributes_json,created_by) VALUES (:item,:lot,CURDATE(),'PENDING','BLOCKED',:attributes,:user)")->execute(['item'=>$item['id'],'lot'=>$lotCode,'attributes'=>json_encode(['manual_reference'=>$reference],JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),'user'=>$user['id']]);
            $lotId=(int)$pdo->lastInsertId();
            $movementId=createInventoryMovementV14($pdo,'RECEIPT','manual_warehouse_entry',0,$reference?:$lotCode,$notes,(int)$user['id'],[['item_id'=>(int)$item['id'],'lot_id'=>$lotId,'warehouse_id'=>(int)$warehouse['id'],'location_id'=>(int)$location['id'],'uom_id'=>(int)$item['base_uom_id'],'qty'=>$quantity,'notes'=>'Entrada automática a WID · '.$notes]]);
            $pdo->prepare("UPDATE inventory_movements SET source_id=:source WHERE id=:id")->execute(['source'=>$movementId,'id'=>$movementId]);
            $qualityType=$item['item_type']==='RAW_FRUIT'?'INBOUND_FRUIT':'INBOUND_MATERIAL';
            $pdo->prepare("INSERT INTO quality_requests (request_number,request_type,inventory_lot_id,target_type,target_id,requested_by,status) VALUES (:number,:type,:lot,'INVENTORY_MOVEMENT',:movement,:user,'REQUESTED')")->execute(['number'=>provisionalNumber('CAL'),'type'=>$qualityType,'lot'=>$lotId,'movement'=>$movementId,'user'=>$user['id']]);
            $qualityId=(int)$pdo->lastInsertId();$qualityNumber=finalNumber('CAL',$qualityId);
            $pdo->prepare("UPDATE quality_requests SET request_number=:number WHERE id=:id")->execute(['number'=>$qualityNumber,'id'=>$qualityId]);
            postMovementV14($pdo,$movementId,(int)$user['id']);
            $movementNumber=(string)safeScalar($pdo,"SELECT movement_number FROM inventory_movements WHERE id=:id",['id'=>$movementId]);
            $recipients=roleRecipientsV15($pdo,['AREA_ADMIN','AREA_MANAGER','APPROVER'],'CALIDAD');
            createAlertV15($pdo,'CALIDAD',$recipients,'QUALITY_REQUESTED','WARNING','Nueva entrada pendiente de Calidad',"{$qualityNumber}: {$item['name']}, lote {$lotCode}, {$quantity} {$item['uom_code']}.",'quality_request',$qualityId,'QUALITY_REQUESTED_MANUAL_'.$movementId);
            writeAudit($pdo,(int)$user['id'],'POST','inventory_movement',$movementId,['movement_number'=>$movementNumber,'direction'=>'ENTRY','item'=>$item['sku'],'lot'=>$lotCode,'quantity'=>$quantity,'uom'=>$item['uom_code'],'warehouse'=>$warehouse['name'],'quality_request'=>$qualityNumber],$notes);
            $pdo->commit();
        }catch(Throwable $error){if($pdo->inTransaction())$pdo->rollBack();throw $error;}
        try{queueNotifications($pdo,$config,'QUALITY_REQUESTED','inventory_movement',$movementId,$recipients,"Nueva solicitud de Calidad {$qualityNumber}","Almacén registró {$movementNumber}. Material: {$item['name']}. Lote: {$lotCode}. Cantidad: {$quantity} {$item['uom_code']}. La existencia está en WID y no estará disponible hasta el dictamen.");}catch(Throwable $ignored){}
        return ['id'=>$movementId,'number'=>$movementNumber,'direction'=>'ENTRY','lot'=>$lotCode,'qualityRequest'=>$qualityNumber];
    }

    $parts=explode('|',requiredString($payload,'source_inventory_key','la existencia de salida',100));
    if(count($parts)!==4||array_filter($parts,static fn(string $value): bool=>!ctype_digit($value)))failRequest('Selecciona una existencia disponible válida.',422);
    [$itemId,$lotId,$warehouseId,$locationId]=array_map('intval',$parts);
    $source=findOne($pdo,"SELECT i.id AS item_id,i.sku,i.name,i.item_type,i.base_uom_id,u.code AS uom_code,u.decimal_places,l.id AS lot_id,l.lot_code,w.id AS warehouse_id,w.name AS warehouse_name,w.warehouse_type,wl.id AS location_id,wl.name AS location_name,COALESCE(SUM(CASE WHEN m.status='POSTED' THEN ml.quantity_delta ELSE 0 END),0) AS available_qty FROM items i INNER JOIN units_of_measure u ON u.id=i.base_uom_id INNER JOIN inventory_lots l ON l.item_id=i.id INNER JOIN warehouses w ON w.id=:warehouse INNER JOIN warehouse_locations wl ON wl.id=:location AND wl.warehouse_id=w.id LEFT JOIN inventory_movement_lines ml ON ml.item_id=i.id AND ml.inventory_lot_id=l.id AND ml.warehouse_id=w.id AND ml.location_id=wl.id LEFT JOIN inventory_movements m ON m.id=ml.movement_id WHERE i.id=:item AND l.id=:lot AND i.is_active=1 AND w.is_active=1 AND wl.is_active=1 AND wl.is_blocked=0 AND wl.location_type IN ('STORAGE','PICKING','SHIPPING') AND l.quality_status IN ('APPROVED','CONDITIONAL') AND l.lot_status='OPEN' GROUP BY i.id,i.sku,i.name,i.item_type,i.base_uom_id,u.code,u.decimal_places,l.id,l.lot_code,w.id,w.name,w.warehouse_type,wl.id,wl.name HAVING available_qty>0",['item'=>$itemId,'lot'=>$lotId,'warehouse'=>$warehouseId,'location'=>$locationId],'La existencia ya no está disponible. Actualiza la pantalla.');
    if($warehouseType!==''&&$warehouseType!==$source['warehouse_type'])failRequest('La existencia no pertenece a este almacén.',422);
    $module=itemModuleV14((string)$source['item_type']);requireAnyPermissionV14($pdo,(int)$user['id'],[$module,'INVENTORY'],'POST');
    $quantity=positiveNumber($payload,'quantity','La cantidad');if((int)$source['decimal_places']===0&&abs($quantity-round($quantity))>0.000001)failRequest('La unidad de este material sólo admite cantidades enteras.',422);if($quantity>(float)$source['available_qty']+0.000001)failRequest('La salida supera la existencia disponible.',409);
    $pdo->beginTransaction();try{$movementId=createInventoryMovementV14($pdo,'OTHER','manual_warehouse_exit',0,$source['lot_code'],$notes,(int)$user['id'],[['item_id'=>(int)$source['item_id'],'lot_id'=>(int)$source['lot_id'],'warehouse_id'=>(int)$source['warehouse_id'],'location_id'=>(int)$source['location_id'],'uom_id'=>(int)$source['base_uom_id'],'qty'=>-$quantity,'notes'=>'Salida de almacén · '.$notes]]);$pdo->prepare("UPDATE inventory_movements SET source_id=:source WHERE id=:id")->execute(['source'=>$movementId,'id'=>$movementId]);postMovementV14($pdo,$movementId,(int)$user['id']);$movementNumber=(string)safeScalar($pdo,"SELECT movement_number FROM inventory_movements WHERE id=:id",['id'=>$movementId]);writeAudit($pdo,(int)$user['id'],'POST','inventory_movement',$movementId,['movement_number'=>$movementNumber,'direction'=>'EXIT','item'=>$source['sku'],'lot'=>$source['lot_code'],'quantity'=>$quantity,'uom'=>$source['uom_code'],'warehouse'=>$source['warehouse_name']],$notes);$pdo->commit();return ['id'=>$movementId,'number'=>$movementNumber,'direction'=>'EXIT','lot'=>$source['lot_code']];}catch(Throwable $error){if($pdo->inTransaction())$pdo->rollBack();throw $error;}
}

function assignProductFormulaV18(PDO $pdo,array $user,array $payload): array
{
    requirePermission($pdo,(int)$user['id'],'BOM_MANAGEMENT','UPDATE');
    $item=findOne($pdo,"SELECT i.id,i.sku,i.name,i.base_uom_id,p.presentation_ml FROM items i INNER JOIN product_presentations p ON p.finished_item_id=i.id WHERE i.id=:id AND i.item_type='FINISHED_GOOD' AND i.is_active=1",['id'=>(int)($payload['finished_item_id']??0)],'Selecciona un producto terminado oficial.');
    $formula=findOne($pdo,"SELECT v.id,f.name FROM oil_formulation_versions v INNER JOIN oil_formulations f ON f.id=v.oil_formulation_id WHERE v.id=:id AND v.status='ACTIVE' AND f.is_active=1",['id'=>(int)($payload['oil_formula_version_id']??0)],'Selecciona una formulación de aceite activa.');
    $effective=validDate((string)($payload['effective_from']??''));$today=(new DateTimeImmutable('today',new DateTimeZone('America/Mexico_City')))->format('Y-m-d');
    $reason=requiredString($payload,'change_reason','el motivo de la asignación',500);
    $pdo->beginTransaction();
    try{
        $currentRows=safeRows($pdo,"SELECT * FROM finished_product_bom_assignments WHERE finished_item_id=:item AND effective_to IS NULL ORDER BY effective_from DESC,id DESC LIMIT 1 FOR UPDATE",['item'=>$item['id']]);$current=$currentRows[0]??null;
        if($current&&$current['assignment_status']==='PENDING_FORMULATION')$effective=(string)$current['effective_from'];
        elseif($effective<$today)failRequest('La vigencia no puede iniciar en una fecha anterior a hoy.',422);
        if($current&&$current['assignment_status']==='ACTIVE'){$nextMonday=(new DateTimeImmutable('next monday',new DateTimeZone('America/Mexico_City')))->format('Y-m-d');if($effective<$nextMonday)failRequest('Un cambio de formulación debe iniciar el próximo lunes o después para no alterar órdenes actuales.',422);}
        $packagingVersion=(int)($payload['packaging_bom_version_id']??($current['packaging_bom_version_id']??0));if(!$packagingVersion)failRequest('El producto no tiene lista de materiales de empaque importada.',409);findOne($pdo,"SELECT bv.id FROM bom_versions bv INNER JOIN bills_of_material b ON b.id=bv.bom_id WHERE bv.id=:version AND b.output_item_id=:item",['version'=>$packagingVersion,'item'=>$item['id']],'La lista de empaque no corresponde al producto seleccionado.');
        $bomCode='BOM-PLAN-'.$item['sku'];$pdo->prepare("INSERT INTO bills_of_material (bom_code,output_item_id,name,is_active,created_by) VALUES (:code,:item,:name,1,:user) ON DUPLICATE KEY UPDATE name=VALUES(name),is_active=1")->execute(['code'=>$bomCode,'item'=>$item['id'],'name'=>'Lista completa · '.$item['name'],'user'=>$user['id']]);$bom=findOne($pdo,"SELECT id FROM bills_of_material WHERE bom_code=:code FOR UPDATE",['code'=>$bomCode],'No se pudo preparar la lista completa.');
        $versionNo=(int)safeScalar($pdo,"SELECT COALESCE(MAX(version_no),0)+1 FROM bom_versions WHERE bom_id=:bom",['bom'=>$bom['id']]);
        $pdo->prepare("UPDATE bom_versions SET effective_to=DATE_SUB(:effective,INTERVAL 1 DAY) WHERE bom_id=:bom AND effective_to IS NULL AND effective_from<:effective_before")->execute(['effective'=>$effective,'bom'=>$bom['id'],'effective_before'=>$effective]);
        $pdo->prepare("INSERT INTO bom_versions (bom_id,version_no,output_qty,output_uom_id,effective_from,status,expected_yield_pct,source_reference,approved_by,approved_at) VALUES (:bom,:version,1,:uom,:effective,'ACTIVE',100,:reference,:user,UTC_TIMESTAMP(6))")->execute(['bom'=>$bom['id'],'version'=>$versionNo,'uom'=>$item['base_uom_id'],'effective'=>$effective,'reference'=>'ASSIGN-'.$item['sku'].'-'.$effective.'-'.substr(hash('sha256',$reason),0,12),'user'=>$user['id']]);$compiled=(int)$pdo->lastInsertId();
        $pdo->prepare("INSERT INTO bom_components (bom_version_id,line_no,component_item_id,component_uom_id,qty_per_output,scrap_pct,is_optional) SELECT :compiled,ROW_NUMBER() OVER (ORDER BY bc.line_no),bc.component_item_id,bc.component_uom_id,bc.qty_per_output,bc.scrap_pct,bc.is_optional FROM bom_components bc WHERE bc.bom_version_id=:packaging")->execute(['compiled'=>$compiled,'packaging'=>$packagingVersion]);
        $line=(int)safeScalar($pdo,"SELECT COALESCE(MAX(line_no),0) FROM bom_components WHERE bom_version_id=:compiled",['compiled'=>$compiled]);$components=safeRows($pdo,"SELECT c.raw_item_id,i.base_uom_id,c.percentage FROM oil_formulation_components c INNER JOIN items i ON i.id=c.raw_item_id WHERE c.oil_formulation_version_id=:formula ORDER BY c.line_no",['formula'=>$formula['id']]);if(!$components)failRequest('La formulación no contiene aceites.',409);$insert=$pdo->prepare("INSERT INTO bom_components (bom_version_id,line_no,component_item_id,component_uom_id,qty_per_output,scrap_pct,is_optional) VALUES (:version,:line,:item,:uom,:qty,0,0)");foreach($components as $component)$insert->execute(['version'=>$compiled,'line'=>++$line,'item'=>$component['raw_item_id'],'uom'=>$component['base_uom_id'],'qty'=>(float)$item['presentation_ml']/1000*(float)$component['percentage']/100]);
        $pdo->prepare("UPDATE bills_of_material b INNER JOIN bom_versions v ON v.bom_id=b.id SET b.is_active=0 WHERE v.id=:packaging")->execute(['packaging'=>$packagingVersion]);
        if($current&&$current['effective_from']===$effective){$pdo->prepare("UPDATE finished_product_bom_assignments SET oil_formula_version_id=:formula,compiled_bom_version_id=:compiled,assignment_status='ACTIVE',change_reason=:reason,created_by=:user WHERE id=:id")->execute(['formula'=>$formula['id'],'compiled'=>$compiled,'reason'=>$reason,'user'=>$user['id'],'id'=>$current['id']]);$assignment=(int)$current['id'];}
        else{if($current)$pdo->prepare("UPDATE finished_product_bom_assignments SET effective_to=DATE_SUB(:effective,INTERVAL 1 DAY),assignment_status='OBSOLETE' WHERE id=:id")->execute(['effective'=>$effective,'id'=>$current['id']]);$pdo->prepare("INSERT INTO finished_product_bom_assignments (finished_item_id,packaging_bom_version_id,oil_formula_version_id,compiled_bom_version_id,effective_from,assignment_status,change_reason,created_by) VALUES (:item,:packaging,:formula,:compiled,:effective,'ACTIVE',:reason,:user)")->execute(['item'=>$item['id'],'packaging'=>$packagingVersion,'formula'=>$formula['id'],'compiled'=>$compiled,'effective'=>$effective,'reason'=>$reason,'user'=>$user['id']]);$assignment=(int)$pdo->lastInsertId();}
        $pdo->prepare("UPDATE production_orders SET bom_assignment_id=:assignment,oil_formula_version_id=:formula WHERE bom_version_id=:compiled")->execute(['assignment'=>$assignment,'formula'=>$formula['id'],'compiled'=>$compiled]);writeAudit($pdo,(int)$user['id'],'UPDATE','finished_product_bom_assignment',$assignment,['product'=>$item['sku'],'formula'=>$formula['name'],'effective_from'=>$effective,'compiled_bom_version'=>$compiled],$reason);$pdo->commit();$runs=recalculateCurrentForecasts($pdo,(int)$user['id']);return ['id'=>$assignment,'product'=>$item['name'],'formula'=>$formula['name'],'effectiveFrom'=>$effective,'compiledBomVersionId'=>$compiled,'mrpRunsUpdated'=>$runs];
    }catch(Throwable $error){if($pdo->inTransaction())$pdo->rollBack();throw $error;}
}

function changePackagingComponentV18(PDO $pdo,array $user,array $payload): array
{
    requirePermission($pdo,(int)$user['id'],'BOM_MANAGEMENT','UPDATE');$item=findOne($pdo,"SELECT id,sku,name FROM items WHERE id=:id AND item_type='FINISHED_GOOD' AND is_active=1",['id'=>(int)($payload['finished_item_id']??0)],'Selecciona un producto terminado oficial.');$component=findOne($pdo,"SELECT id,sku,name,base_uom_id FROM items WHERE id=:id AND item_type='PACKAGING' AND is_active=1",['id'=>(int)($payload['component_item_id']??0)],'Selecciona un material de empaque oficial.');$qty=positiveNumber($payload,'component_quantity','La cantidad por botella');$effective=validDate((string)($payload['effective_from']??''));$today=(new DateTimeImmutable('today',new DateTimeZone('America/Mexico_City')))->format('Y-m-d');if($effective<$today)failRequest('La vigencia no puede iniciar antes de hoy.',422);$reason=requiredString($payload,'change_reason','el motivo del cambio',500);$current=findOne($pdo,"SELECT * FROM finished_product_bom_assignments WHERE finished_item_id=:item AND effective_to IS NULL ORDER BY effective_from DESC,id DESC LIMIT 1",['item'=>$item['id']],'El producto no tiene lista de empaque importada.');if($current['assignment_status']==='ACTIVE'){$nextMonday=(new DateTimeImmutable('next monday',new DateTimeZone('America/Mexico_City')))->format('Y-m-d');if($effective<$nextMonday)failRequest('El cambio debe iniciar el próximo lunes o después para no alterar órdenes actuales.',422);}
    $old=findOne($pdo,"SELECT bv.id,bv.bom_id,bv.output_qty,bv.output_uom_id FROM bom_versions bv WHERE bv.id=:id",['id'=>$current['packaging_bom_version_id']],'No se localizó la versión de empaque actual.');$pdo->beginTransaction();try{$version=(int)safeScalar($pdo,"SELECT COALESCE(MAX(version_no),0)+1 FROM bom_versions WHERE bom_id=:bom",['bom'=>$old['bom_id']]);$pdo->prepare("UPDATE bom_versions SET effective_to=CASE WHEN effective_from<:effective_compare THEN DATE_SUB(:effective,INTERVAL 1 DAY) ELSE effective_from END,status='OBSOLETE' WHERE id=:id")->execute(['effective_compare'=>$effective,'effective'=>$effective,'id'=>$old['id']]);$pdo->prepare("INSERT INTO bom_versions (bom_id,version_no,output_qty,output_uom_id,effective_from,status,expected_yield_pct,source_reference,approved_by,approved_at) VALUES (:bom,:version,:output,:uom,:effective,'ACTIVE',100,:source,:user,UTC_TIMESTAMP(6))")->execute(['bom'=>$old['bom_id'],'version'=>$version,'output'=>$old['output_qty'],'uom'=>$old['output_uom_id'],'effective'=>$effective,'source'=>'PACK-CHANGE-'.$item['sku'].'-'.$effective.'-'.substr(hash('sha256',$reason),0,10),'user'=>$user['id']]);$newVersion=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO bom_components (bom_version_id,line_no,component_item_id,component_uom_id,qty_per_output,scrap_pct,is_optional) SELECT :new_version,ROW_NUMBER() OVER (ORDER BY line_no),component_item_id,CASE WHEN component_item_id=:component THEN :new_uom ELSE component_uom_id END,CASE WHEN component_item_id=:component_qty THEN :qty ELSE qty_per_output END,scrap_pct,is_optional FROM bom_components WHERE bom_version_id=:old_version")->execute(['new_version'=>$newVersion,'component'=>$component['id'],'new_uom'=>$component['base_uom_id'],'component_qty'=>$component['id'],'qty'=>$qty,'old_version'=>$old['id']]);if(!safeScalar($pdo,"SELECT COUNT(*) FROM bom_components WHERE bom_version_id=:version AND component_item_id=:component",['version'=>$newVersion,'component'=>$component['id']])){$line=(int)safeScalar($pdo,"SELECT COALESCE(MAX(line_no),0)+1 FROM bom_components WHERE bom_version_id=:version",['version'=>$newVersion]);$pdo->prepare("INSERT INTO bom_components (bom_version_id,line_no,component_item_id,component_uom_id,qty_per_output,scrap_pct,is_optional) VALUES (:version,:line,:component,:uom,:qty,0,0)")->execute(['version'=>$newVersion,'line'=>$line,'component'=>$component['id'],'uom'=>$component['base_uom_id'],'qty'=>$qty]);}
        if($current['assignment_status']!=='ACTIVE'){if($current['effective_from']===$effective)$pdo->prepare("UPDATE finished_product_bom_assignments SET packaging_bom_version_id=:version,change_reason=:reason,created_by=:user WHERE id=:id")->execute(['version'=>$newVersion,'reason'=>$reason,'user'=>$user['id'],'id'=>$current['id']]);else{$pdo->prepare("UPDATE finished_product_bom_assignments SET effective_to=DATE_SUB(:effective,INTERVAL 1 DAY),assignment_status='OBSOLETE' WHERE id=:id")->execute(['effective'=>$effective,'id'=>$current['id']]);$pdo->prepare("INSERT INTO finished_product_bom_assignments (finished_item_id,packaging_bom_version_id,effective_from,assignment_status,change_reason,created_by) VALUES (:item,:version,:effective,'PENDING_FORMULATION',:reason,:user)")->execute(['item'=>$item['id'],'version'=>$newVersion,'effective'=>$effective,'reason'=>$reason,'user'=>$user['id']]);}writeAudit($pdo,(int)$user['id'],'UPDATE','packaging_bom_version',$newVersion,['product'=>$item['sku'],'component'=>$component['sku'],'quantity'=>$qty,'effective_from'=>$effective],$reason);$pdo->commit();return ['id'=>$newVersion,'product'=>$item['name'],'component'=>$component['name'],'requiresFormula'=>true];}
        $formula=(int)$current['oil_formula_version_id'];
        $pdo->commit();
        try{
            $assignment=assignProductFormulaV18($pdo,$user,['finished_item_id'=>$item['id'],'oil_formula_version_id'=>$formula,'packaging_bom_version_id'=>$newVersion,'effective_from'=>$effective,'change_reason'=>$reason]);
        }catch(Throwable $assignmentError){
            $pdo->beginTransaction();
            try{
                $pdo->prepare("DELETE FROM bom_versions WHERE id=:id")->execute(['id'=>$newVersion]);
                $pdo->prepare("UPDATE bom_versions SET effective_to=NULL,status='ACTIVE' WHERE id=:id")->execute(['id'=>$old['id']]);
                $pdo->commit();
            }catch(Throwable $restoreError){
                if($pdo->inTransaction())$pdo->rollBack();
            }
            throw $assignmentError;
        }
        writeAudit($pdo,(int)$user['id'],'UPDATE','packaging_bom_version',$newVersion,['product'=>$item['sku'],'component'=>$component['sku'],'quantity'=>$qty,'effective_from'=>$effective],$reason);
        return ['id'=>$newVersion,'product'=>$item['name'],'component'=>$component['name'],'assignment'=>$assignment];
    }catch(Throwable $error){if($pdo->inTransaction())$pdo->rollBack();throw $error;}
}

function createPlannedArrivalV18(PDO $pdo,array $user,array $payload): array
{
    requirePermission($pdo,(int)$user['id'],'PLANNED_ARRIVALS','CREATE');$item=findOne($pdo,"SELECT i.id,i.name,i.item_type,i.base_uom_id,w.id AS warehouse_id FROM items i INNER JOIN warehouses w ON w.id=:warehouse AND w.is_active=1 AND w.warehouse_type=CASE WHEN i.item_type IN ('RAW_FRUIT','RAW_OTHER','BULK_OIL') THEN 'RAW_MATERIAL' WHEN i.item_type='PACKAGING' THEN 'PACKAGING' WHEN i.item_type='FINISHED_GOOD' THEN 'FINISHED_GOODS' ELSE 'NONE' END WHERE i.id=:item AND i.is_active=1",['item'=>(int)($payload['item_id']??0),'warehouse'=>(int)($payload['warehouse_id']??0)],'El material y el almacén no corresponden.');$week=validDate((string)($payload['planned_week']??''));if((int)(new DateTimeImmutable($week))->format('N')!==1)failRequest('Selecciona el lunes de la semana planeada.',422);$qty=positiveNumber($payload,'expected_qty','La cantidad esperada');$supplier=(int)($payload['supplier_id']??0)?:null;if($supplier&&!safeScalar($pdo,"SELECT COUNT(*) FROM suppliers WHERE id=:id AND is_active=1",['id'=>$supplier]))failRequest('El proveedor no es válido.',422);$pdo->prepare("INSERT INTO planned_material_arrivals (arrival_number,item_id,warehouse_id,planned_week,expected_qty,uom_id,supplier_id,status,notes,created_by) VALUES (:number,:item,:warehouse,:week,:qty,:uom,:supplier,'PLANNED',:notes,:user)")->execute(['number'=>provisionalNumber('LLP'),'item'=>$item['id'],'warehouse'=>$item['warehouse_id'],'week'=>$week,'qty'=>$qty,'uom'=>$item['base_uom_id'],'supplier'=>$supplier,'notes'=>optionalString($payload,'notes',1000),'user'=>$user['id']]);$id=(int)$pdo->lastInsertId();$number=finalNumber('LLP',$id);$pdo->prepare("UPDATE planned_material_arrivals SET arrival_number=:number WHERE id=:id")->execute(['number'=>$number,'id'=>$id]);writeAudit($pdo,(int)$user['id'],'CREATE','planned_material_arrival',$id,['number'=>$number,'item'=>$item['name'],'week'=>$week,'quantity'=>$qty]);return ['id'=>$id,'number'=>$number];
}

function setInitialInventoryV18(PDO $pdo,array $user,array $payload): array
{
    if(!isSuperAdmin($pdo,(int)$user['id']))failRequest('Solo el administrador del sistema puede habilitar o cerrar la captura inicial.',403);$warehouse=findOne($pdo,"SELECT id,name FROM warehouses WHERE id=:id AND code IN ('MP','EMPAQUE','PT')",['id'=>(int)($payload['warehouse_id']??0)],'Selecciona uno de los tres almacenes principales.');$enabled=filter_var($payload['enabled']??false,FILTER_VALIDATE_BOOLEAN);$pdo->prepare("INSERT INTO warehouse_inventory_settings (warehouse_id,initial_capture_enabled,disabled_at,disabled_by) VALUES (:warehouse,:enabled,:disabled_at,:disabled_by) ON DUPLICATE KEY UPDATE initial_capture_enabled=VALUES(initial_capture_enabled),disabled_at=VALUES(disabled_at),disabled_by=VALUES(disabled_by)")->execute(['warehouse'=>$warehouse['id'],'enabled'=>$enabled?1:0,'disabled_at'=>$enabled?null:gmdate('Y-m-d H:i:s'),'disabled_by'=>$enabled?null:$user['id']]);writeAudit($pdo,(int)$user['id'],'UPDATE','warehouse_inventory_setting',$warehouse['id'],['enabled'=>$enabled]);return ['id'=>(int)$warehouse['id'],'enabled'=>$enabled];
}

function createProductionOrderV18(PDO $pdo,array $user,array $payload): array
{
    $start=validDate(substr((string)($payload['planned_start']??''),0,10));$assignment=findOne($pdo,"SELECT a.id,a.compiled_bom_version_id,a.oil_formula_version_id FROM finished_product_bom_assignments a WHERE a.finished_item_id=:item AND a.assignment_status='ACTIVE' AND a.effective_from<=:start AND (a.effective_to IS NULL OR a.effective_to>=:start_end) ORDER BY a.effective_from DESC LIMIT 1",['item'=>(int)($payload['finished_item_id']??0),'start'=>$start,'start_end'=>$start],'El producto todavía no tiene una formulación de aceite vigente. Asígnala en Listas de materiales.');$payload['bom_version_id']=$assignment['compiled_bom_version_id'];$result=createProductionOrderV14($pdo,$user,$payload);$pdo->prepare("UPDATE production_orders SET bom_assignment_id=:assignment,oil_formula_version_id=:formula WHERE id=:id")->execute(['assignment'=>$assignment['id'],'formula'=>$assignment['oil_formula_version_id'],'id'=>$result['id']]);return $result;
}

function createProductionCompletionV18(PDO $pdo,array $user,array $payload,array $config): array
{
    $result=createProductionCompletionV14($pdo,$user,$payload);
    if(empty($result['qualityRequest']))return $result;
    $qualityId=(int)safeScalar($pdo,"SELECT id FROM quality_requests WHERE request_number=:number",['number'=>$result['qualityRequest']]);
    $recipients=roleRecipientsV15($pdo,['AREA_ADMIN','AREA_MANAGER','APPROVER'],'CALIDAD');
    $message="{$result['qualityRequest']}: producto terminado {$result['number']}, lote {$result['lot']}. La existencia permanece en WID hasta registrar el dictamen.";
    try{createAlertV15($pdo,'CALIDAD',$recipients,'QUALITY_REQUESTED','WARNING','Producto terminado pendiente de Calidad',$message,'quality_request',$qualityId,'QUALITY_REQUESTED_PRODUCTION_'.$result['id']);queueNotifications($pdo,$config,'QUALITY_REQUESTED','production_completion',(int)$result['id'],$recipients,"Nueva solicitud de Calidad {$result['qualityRequest']}",$message);}catch(Throwable $ignored){}
    return $result;
}

function rebuildWeeklyForecastV18(PDO $pdo,int $forecastVersionId): int
{
    if(!tableExistsV18($pdo,'forecast_weekly_lines'))return 0;$pdo->prepare("DELETE FROM forecast_weekly_lines WHERE forecast_version_id=:version")->execute(['version'=>$forecastVersionId]);$monthly=safeRows($pdo,"SELECT finished_item_id,period_start,forecast_qty,id FROM forecast_lines WHERE forecast_version_id=:version ORDER BY period_start,finished_item_id",['version'=>$forecastVersionId]);$insert=$pdo->prepare("INSERT INTO forecast_weekly_lines (forecast_version_id,finished_item_id,week_start,forecast_qty,allocation_method,source_month,source_row) VALUES (:version,:item,:week,:qty,'WORKDAYS',:month,:source)");$count=0;foreach($monthly as $row){$start=new DateTimeImmutable((string)$row['period_start']);$month=(int)$start->format('n');$days=(int)$start->format('t');$byWeek=[];for($day=1;$day<=$days;$day++){$date=$start->setDate((int)$start->format('Y'),$month,$day);if((int)$date->format('N')>5)continue;$monday=$date->modify('monday this week')->format('Y-m-d');$byWeek[$monday]=($byWeek[$monday]??0)+1;}$totalDays=array_sum($byWeek);$remaining=(float)$row['forecast_qty'];$index=0;$last=count($byWeek)-1;foreach($byWeek as $week=>$workdays){$qty=$index===$last?$remaining:round((float)$row['forecast_qty']*$workdays/$totalDays,6);$remaining-=$qty;if($qty>0){$insert->execute(['version'=>$forecastVersionId,'item'=>$row['finished_item_id'],'week'=>$week,'qty'=>$qty,'month'=>$month,'source'=>$row['id']]);$count++;}$index++;}}return $count;
}
